//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by jni4net. See http://jni4net.sourceforge.net/ 
//     Runtime Version:4.0.30319.296
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASquared.SymbolicMath {
    
    
    #region Component Designer generated code 
    public partial class SymbolicMatrix_ {
        
        public static global::java.lang.Class _class {
            get {
                return global::ASquared.SymbolicMath.@__SymbolicMatrix.staticClass;
            }
        }
    }
    #endregion
    
    #region Component Designer generated code 
    [global::net.sf.jni4net.attributes.JavaProxyAttribute(typeof(global::ASquared.SymbolicMath.SymbolicMatrix), typeof(global::ASquared.SymbolicMath.SymbolicMatrix_))]
    [global::net.sf.jni4net.attributes.ClrWrapperAttribute(typeof(global::ASquared.SymbolicMath.SymbolicMatrix), typeof(global::ASquared.SymbolicMath.SymbolicMatrix_))]
    internal sealed partial class @__SymbolicMatrix : global::java.lang.Object {
        
        internal new static global::java.lang.Class staticClass;
        
        private @__SymbolicMatrix(global::net.sf.jni4net.jni.JNIEnv @__env) : 
                base(@__env) {
        }
        
        private static void InitJNI(global::net.sf.jni4net.jni.JNIEnv @__env, java.lang.Class @__class) {
            global::ASquared.SymbolicMath.@__SymbolicMatrix.staticClass = @__class;
        }
        
        private static global::System.Collections.Generic.List<global::net.sf.jni4net.jni.JNINativeMethod> @__Init(global::net.sf.jni4net.jni.JNIEnv @__env, global::java.lang.Class @__class) {
            global::System.Type @__type = typeof(__SymbolicMatrix);
            global::System.Collections.Generic.List<global::net.sf.jni4net.jni.JNINativeMethod> methods = new global::System.Collections.Generic.List<global::net.sf.jni4net.jni.JNINativeMethod>();
            methods.Add(global::net.sf.jni4net.jni.JNINativeMethod.Create(@__type, "getTabularValues", "TabularValues0", "()Lsystem/Object;"));
            methods.Add(global::net.sf.jni4net.jni.JNINativeMethod.Create(@__type, "setTabularValues", "TabularValues1", "(Lsystem/Object;)V"));
            methods.Add(global::net.sf.jni4net.jni.JNINativeMethod.Create(@__type, "getValues", "Values2", "()[Lasquared/symbolicmath/Symbol;"));
            methods.Add(global::net.sf.jni4net.jni.JNINativeMethod.Create(@__type, "getNumberOfRows", "NumberOfRows3", "()I"));
            methods.Add(global::net.sf.jni4net.jni.JNINativeMethod.Create(@__type, "getNumberOfColumns", "NumberOfColumns4", "()I"));
            methods.Add(global::net.sf.jni4net.jni.JNINativeMethod.Create(@__type, "getNumberOfElements", "NumberOfElements5", "()I"));
            methods.Add(global::net.sf.jni4net.jni.JNINativeMethod.Create(@__type, "getLength", "Length6", "()I"));
            methods.Add(global::net.sf.jni4net.jni.JNINativeMethod.Create(@__type, "getItem", "Item7", "(I)Lasquared/symbolicmath/Symbol;"));
            methods.Add(global::net.sf.jni4net.jni.JNINativeMethod.Create(@__type, "setItem", "Item8", "(ILasquared/symbolicmath/Symbol;)V"));
            methods.Add(global::net.sf.jni4net.jni.JNINativeMethod.Create(@__type, "getItem", "Item9", "(II)Lasquared/symbolicmath/Symbol;"));
            methods.Add(global::net.sf.jni4net.jni.JNINativeMethod.Create(@__type, "setItem", "Item10", "(IILasquared/symbolicmath/Symbol;)V"));
            methods.Add(global::net.sf.jni4net.jni.JNINativeMethod.Create(@__type, "Copy", "Copy11", "()Lasquared/symbolicmath/SymbolicMatrix;"));
            methods.Add(global::net.sf.jni4net.jni.JNINativeMethod.Create(@__type, "ToArray", "ToArray12", "()[Lasquared/symbolicmath/Symbol;"));
            methods.Add(global::net.sf.jni4net.jni.JNINativeMethod.Create(@__type, "To1DArray", "To1DArray13", "()[Lasquared/symbolicmath/Symbol;"));
            methods.Add(global::net.sf.jni4net.jni.JNINativeMethod.Create(@__type, "ConvertArray", "ConvertArray14", "([Lasquared/symbolicmath/Symbol;Lasquared/symbolicmath/OrientationOption;)[Lasqua" +
                        "red/symbolicmath/Symbol;"));
            methods.Add(global::net.sf.jni4net.jni.JNINativeMethod.Create(@__type, "ConvertArrayToDataTable", "ConvertArrayToDataTable16", "([Lasquared/symbolicmath/Symbol;Lasquared/symbolicmath/OrientationOption;)Lsystem" +
                        "/Object;"));
            methods.Add(global::net.sf.jni4net.jni.JNINativeMethod.Create(@__type, "ConvertArrayToDataTable", "ConvertArrayToDataTable17", "([Lasquared/symbolicmath/Symbol;)Lsystem/Object;"));
            methods.Add(global::net.sf.jni4net.jni.JNINativeMethod.Create(@__type, "BuildTable", "BuildTable18", "(IILasquared/symbolicmath/Symbol;)Lsystem/Object;"));
            methods.Add(global::net.sf.jni4net.jni.JNINativeMethod.Create(@__type, "FromArray", "FromArray19", "([Lasquared/symbolicmath/Symbol;)Lasquared/symbolicmath/SymbolicMatrix;"));
            methods.Add(global::net.sf.jni4net.jni.JNINativeMethod.Create(@__type, "InsertRowsAt", "InsertRowsAt20", "(Lasquared/symbolicmath/SymbolicMatrix;I)V"));
            methods.Add(global::net.sf.jni4net.jni.JNINativeMethod.Create(@__type, "InsertColsAt", "InsertColsAt21", "(Lasquared/symbolicmath/SymbolicMatrix;I)V"));
            methods.Add(global::net.sf.jni4net.jni.JNINativeMethod.Create(@__type, "AppendRows", "AppendRows22", "(Lasquared/symbolicmath/SymbolicMatrix;)V"));
            methods.Add(global::net.sf.jni4net.jni.JNINativeMethod.Create(@__type, "AppendRows", "AppendRows23", "(I)V"));
            methods.Add(global::net.sf.jni4net.jni.JNINativeMethod.Create(@__type, "AppendCols", "AppendCols24", "(Lasquared/symbolicmath/SymbolicMatrix;)V"));
            methods.Add(global::net.sf.jni4net.jni.JNINativeMethod.Create(@__type, "AppendCols", "AppendCols25", "(I)V"));
            methods.Add(global::net.sf.jni4net.jni.JNINativeMethod.Create(@__type, "RemoveRowAt", "RemoveRowAt26", "(I)Lasquared/symbolicmath/SymbolicMatrix;"));
            methods.Add(global::net.sf.jni4net.jni.JNINativeMethod.Create(@__type, "RemoveColAt", "RemoveColAt27", "(I)Lasquared/symbolicmath/SymbolicMatrix;"));
            methods.Add(global::net.sf.jni4net.jni.JNINativeMethod.Create(@__type, "MoveRow", "MoveRow28", "(II)V"));
            methods.Add(global::net.sf.jni4net.jni.JNINativeMethod.Create(@__type, "MoveCol", "MoveCol29", "(II)V"));
            methods.Add(global::net.sf.jni4net.jni.JNINativeMethod.Create(@__type, "ReplaceRow", "ReplaceRow30", "(ILasquared/symbolicmath/SymbolicMatrix;)V"));
            methods.Add(global::net.sf.jni4net.jni.JNINativeMethod.Create(@__type, "ReplaceCol", "ReplaceCol31", "(ILasquared/symbolicmath/SymbolicMatrix;)V"));
            methods.Add(global::net.sf.jni4net.jni.JNINativeMethod.Create(@__type, "GetRow", "GetRow32", "(I)Lasquared/symbolicmath/SymbolicMatrix;"));
            methods.Add(global::net.sf.jni4net.jni.JNINativeMethod.Create(@__type, "GetCol", "GetCol33", "(I)Lasquared/symbolicmath/SymbolicMatrix;"));
            methods.Add(global::net.sf.jni4net.jni.JNINativeMethod.Create(@__type, "GetRows", "GetRows34", "([I)Lasquared/symbolicmath/SymbolicMatrix;"));
            methods.Add(global::net.sf.jni4net.jni.JNINativeMethod.Create(@__type, "GetCols", "GetCols35", "([I)Lasquared/symbolicmath/SymbolicMatrix;"));
            methods.Add(global::net.sf.jni4net.jni.JNINativeMethod.Create(@__type, "GetRows", "GetRows36", "(II)Lasquared/symbolicmath/SymbolicMatrix;"));
            methods.Add(global::net.sf.jni4net.jni.JNINativeMethod.Create(@__type, "GetCols", "GetCols37", "(II)Lasquared/symbolicmath/SymbolicMatrix;"));
            methods.Add(global::net.sf.jni4net.jni.JNINativeMethod.Create(@__type, "GetRowArray", "GetRowArray38", "(I)[Lasquared/symbolicmath/Symbol;"));
            methods.Add(global::net.sf.jni4net.jni.JNINativeMethod.Create(@__type, "GetColArray", "GetColArray39", "(I)[Lasquared/symbolicmath/Symbol;"));
            methods.Add(global::net.sf.jni4net.jni.JNINativeMethod.Create(@__type, "Add", "Add40", "(Lasquared/symbolicmath/SymbolicMatrix;)Lasquared/symbolicmath/SymbolicMatrix;"));
            methods.Add(global::net.sf.jni4net.jni.JNINativeMethod.Create(@__type, "Add", "Add41", "(Lasquared/symbolicmath/Symbol;)Lasquared/symbolicmath/SymbolicMatrix;"));
            methods.Add(global::net.sf.jni4net.jni.JNINativeMethod.Create(@__type, "Mult", "Mult42", "(Lasquared/symbolicmath/Symbol;)Lasquared/symbolicmath/SymbolicMatrix;"));
            methods.Add(global::net.sf.jni4net.jni.JNINativeMethod.Create(@__type, "Mult", "Mult43", "(Lasquared/symbolicmath/SymbolicMatrix;Lasquared/TransposeOption;)Lasquared/symbo" +
                        "licmath/SymbolicMatrix;"));
            methods.Add(global::net.sf.jni4net.jni.JNINativeMethod.Create(@__type, "ElementwiseMult", "ElementwiseMult44", "(Lasquared/symbolicmath/SymbolicMatrix;)Lasquared/symbolicmath/SymbolicMatrix;"));
            methods.Add(global::net.sf.jni4net.jni.JNINativeMethod.Create(@__type, "ElementwiseDivide", "ElementwiseDivide45", "(Lasquared/symbolicmath/SymbolicMatrix;)Lasquared/symbolicmath/SymbolicMatrix;"));
            methods.Add(global::net.sf.jni4net.jni.JNINativeMethod.Create(@__type, "Pow", "Pow46", "(I)Lasquared/symbolicmath/SymbolicMatrix;"));
            methods.Add(global::net.sf.jni4net.jni.JNINativeMethod.Create(@__type, "Transpose", "Transpose47", "()Lasquared/symbolicmath/SymbolicMatrix;"));
            methods.Add(global::net.sf.jni4net.jni.JNINativeMethod.Create(@__type, "Pivot", "Pivot48", "(II)V"));
            methods.Add(global::net.sf.jni4net.jni.JNINativeMethod.Create(@__type, "RREF", "RREF49", "()V"));
            methods.Add(global::net.sf.jni4net.jni.JNINativeMethod.Create(@__type, "Inverse", "Inverse50", "()Lasquared/symbolicmath/SymbolicMatrix;"));
            methods.Add(global::net.sf.jni4net.jni.JNINativeMethod.Create(@__type, "SolveLinearSys", "SolveLinearSys51", "(Lasquared/symbolicmath/SymbolicMatrix;Lasquared/symbolicmath/SymbolicMatrix;)Las" +
                        "quared/symbolicmath/SymbolicMatrix;"));
            methods.Add(global::net.sf.jni4net.jni.JNINativeMethod.Create(@__type, "FromString", "FromString52", "(Ljava/lang/String;)Lasquared/symbolicmath/SymbolicMatrix;"));
            methods.Add(global::net.sf.jni4net.jni.JNINativeMethod.Create(@__type, "Identity", "Identity53", "(I)Lasquared/symbolicmath/SymbolicMatrix;"));
            methods.Add(global::net.sf.jni4net.jni.JNINativeMethod.Create(@__type, "__ctorSymbolicMatrix0", "__ctorSymbolicMatrix0", "(Lnet/sf/jni4net/inj/IClrProxy;I)V"));
            methods.Add(global::net.sf.jni4net.jni.JNINativeMethod.Create(@__type, "__ctorSymbolicMatrix1", "__ctorSymbolicMatrix1", "(Lnet/sf/jni4net/inj/IClrProxy;ILasquared/symbolicmath/Symbol;)V"));
            methods.Add(global::net.sf.jni4net.jni.JNINativeMethod.Create(@__type, "__ctorSymbolicMatrix2", "__ctorSymbolicMatrix2", "(Lnet/sf/jni4net/inj/IClrProxy;II)V"));
            methods.Add(global::net.sf.jni4net.jni.JNINativeMethod.Create(@__type, "__ctorSymbolicMatrix3", "__ctorSymbolicMatrix3", "(Lnet/sf/jni4net/inj/IClrProxy;IILasquared/symbolicmath/Symbol;)V"));
            methods.Add(global::net.sf.jni4net.jni.JNINativeMethod.Create(@__type, "__ctorSymbolicMatrix4", "__ctorSymbolicMatrix4", "(Lnet/sf/jni4net/inj/IClrProxy;[Lasquared/symbolicmath/Symbol;)V"));
            methods.Add(global::net.sf.jni4net.jni.JNINativeMethod.Create(@__type, "__ctorSymbolicMatrix5", "__ctorSymbolicMatrix5", "(Lnet/sf/jni4net/inj/IClrProxy;[Lasquared/symbolicmath/Symbol;Lasquared/symbolicm" +
                        "ath/OrientationOption;)V"));
            methods.Add(global::net.sf.jni4net.jni.JNINativeMethod.Create(@__type, "__ctorSymbolicMatrix6", "__ctorSymbolicMatrix6", "(Lnet/sf/jni4net/inj/IClrProxy;Lsystem/Object;)V"));
            return methods;
        }
        
        private static global::net.sf.jni4net.utils.JniHandle TabularValues0(global::System.IntPtr @__envp, global::net.sf.jni4net.utils.JniLocalHandle @__obj) {
            // ()Lsystem/Object;
            // ()LSystem/Data/DataTable;
            global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.Wrap(@__envp);
            global::net.sf.jni4net.utils.JniHandle @__return = default(global::net.sf.jni4net.utils.JniHandle);
            try {
            global::ASquared.SymbolicMath.SymbolicMatrix @__real = global::net.sf.jni4net.utils.Convertor.StrongJp2C<global::ASquared.SymbolicMath.SymbolicMatrix>(@__env, @__obj);
            @__return = global::net.sf.jni4net.utils.Convertor.StrongC2Jp<global::System.Data.DataTable>(@__env, @__real.TabularValues);
            }catch (global::System.Exception __ex){@__env.ThrowExisting(__ex);}
            return @__return;
        }
        
        private static void TabularValues1(global::System.IntPtr @__envp, global::net.sf.jni4net.utils.JniLocalHandle @__obj, global::net.sf.jni4net.utils.JniLocalHandle value) {
            // (Lsystem/Object;)V
            // (LSystem/Data/DataTable;)V
            global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.Wrap(@__envp);
            try {
            global::ASquared.SymbolicMath.SymbolicMatrix @__real = global::net.sf.jni4net.utils.Convertor.StrongJp2C<global::ASquared.SymbolicMath.SymbolicMatrix>(@__env, @__obj);
            @__real.TabularValues = global::net.sf.jni4net.utils.Convertor.StrongJp2C<global::System.Data.DataTable>(@__env, value);
            }catch (global::System.Exception __ex){@__env.ThrowExisting(__ex);}
        }
        
        private static global::net.sf.jni4net.utils.JniHandle Values2(global::System.IntPtr @__envp, global::net.sf.jni4net.utils.JniLocalHandle @__obj) {
            // ()[Lasquared/symbolicmath/Symbol;
            // ()[LASquared/SymbolicMath/Symbol;
            global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.Wrap(@__envp);
            global::net.sf.jni4net.utils.JniHandle @__return = default(global::net.sf.jni4net.utils.JniHandle);
            try {
            global::ASquared.SymbolicMath.SymbolicMatrix @__real = global::net.sf.jni4net.utils.Convertor.StrongJp2C<global::ASquared.SymbolicMath.SymbolicMatrix>(@__env, @__obj);
            @__return = global::net.sf.jni4net.utils.Convertor.ArrayStrongC2Jp<global::ASquared.SymbolicMath.Symbol[,], global::ASquared.SymbolicMath.Symbol>(@__env, @__real.Values);
            }catch (global::System.Exception __ex){@__env.ThrowExisting(__ex);}
            return @__return;
        }
        
        private static int NumberOfRows3(global::System.IntPtr @__envp, global::net.sf.jni4net.utils.JniLocalHandle @__obj) {
            // ()I
            // ()I
            global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.Wrap(@__envp);
            int @__return = default(int);
            try {
            global::ASquared.SymbolicMath.SymbolicMatrix @__real = global::net.sf.jni4net.utils.Convertor.StrongJp2C<global::ASquared.SymbolicMath.SymbolicMatrix>(@__env, @__obj);
            @__return = ((int)(@__real.NumberOfRows));
            }catch (global::System.Exception __ex){@__env.ThrowExisting(__ex);}
            return @__return;
        }
        
        private static int NumberOfColumns4(global::System.IntPtr @__envp, global::net.sf.jni4net.utils.JniLocalHandle @__obj) {
            // ()I
            // ()I
            global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.Wrap(@__envp);
            int @__return = default(int);
            try {
            global::ASquared.SymbolicMath.SymbolicMatrix @__real = global::net.sf.jni4net.utils.Convertor.StrongJp2C<global::ASquared.SymbolicMath.SymbolicMatrix>(@__env, @__obj);
            @__return = ((int)(@__real.NumberOfColumns));
            }catch (global::System.Exception __ex){@__env.ThrowExisting(__ex);}
            return @__return;
        }
        
        private static int NumberOfElements5(global::System.IntPtr @__envp, global::net.sf.jni4net.utils.JniLocalHandle @__obj) {
            // ()I
            // ()I
            global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.Wrap(@__envp);
            int @__return = default(int);
            try {
            global::ASquared.SymbolicMath.SymbolicMatrix @__real = global::net.sf.jni4net.utils.Convertor.StrongJp2C<global::ASquared.SymbolicMath.SymbolicMatrix>(@__env, @__obj);
            @__return = ((int)(@__real.NumberOfElements));
            }catch (global::System.Exception __ex){@__env.ThrowExisting(__ex);}
            return @__return;
        }
        
        private static int Length6(global::System.IntPtr @__envp, global::net.sf.jni4net.utils.JniLocalHandle @__obj) {
            // ()I
            // ()I
            global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.Wrap(@__envp);
            int @__return = default(int);
            try {
            global::ASquared.SymbolicMath.SymbolicMatrix @__real = global::net.sf.jni4net.utils.Convertor.StrongJp2C<global::ASquared.SymbolicMath.SymbolicMatrix>(@__env, @__obj);
            @__return = ((int)(@__real.Length));
            }catch (global::System.Exception __ex){@__env.ThrowExisting(__ex);}
            return @__return;
        }
        
        private static global::net.sf.jni4net.utils.JniHandle Item7(global::System.IntPtr @__envp, global::net.sf.jni4net.utils.JniLocalHandle @__obj, int index) {
            // (I)Lasquared/symbolicmath/Symbol;
            // (I)LASquared/SymbolicMath/Symbol;
            global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.Wrap(@__envp);
            global::net.sf.jni4net.utils.JniHandle @__return = default(global::net.sf.jni4net.utils.JniHandle);
            try {
            global::ASquared.SymbolicMath.SymbolicMatrix @__real = global::net.sf.jni4net.utils.Convertor.StrongJp2C<global::ASquared.SymbolicMath.SymbolicMatrix>(@__env, @__obj);
            @__return = global::net.sf.jni4net.utils.Convertor.StrongC2Jp<global::ASquared.SymbolicMath.Symbol>(@__env, @__real[index]);
            }catch (global::System.Exception __ex){@__env.ThrowExisting(__ex);}
            return @__return;
        }
        
        private static void Item8(global::System.IntPtr @__envp, global::net.sf.jni4net.utils.JniLocalHandle @__obj, int index, global::net.sf.jni4net.utils.JniLocalHandle value) {
            // (ILasquared/symbolicmath/Symbol;)V
            // (ILASquared/SymbolicMath/Symbol;)V
            global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.Wrap(@__envp);
            try {
            global::ASquared.SymbolicMath.SymbolicMatrix @__real = global::net.sf.jni4net.utils.Convertor.StrongJp2C<global::ASquared.SymbolicMath.SymbolicMatrix>(@__env, @__obj);
            @__real[index] = global::net.sf.jni4net.utils.Convertor.StrongJp2C<global::ASquared.SymbolicMath.Symbol>(@__env, value);
            }catch (global::System.Exception __ex){@__env.ThrowExisting(__ex);}
        }
        
        private static global::net.sf.jni4net.utils.JniHandle Item9(global::System.IntPtr @__envp, global::net.sf.jni4net.utils.JniLocalHandle @__obj, int row, int col) {
            // (II)Lasquared/symbolicmath/Symbol;
            // (II)LASquared/SymbolicMath/Symbol;
            global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.Wrap(@__envp);
            global::net.sf.jni4net.utils.JniHandle @__return = default(global::net.sf.jni4net.utils.JniHandle);
            try {
            global::ASquared.SymbolicMath.SymbolicMatrix @__real = global::net.sf.jni4net.utils.Convertor.StrongJp2C<global::ASquared.SymbolicMath.SymbolicMatrix>(@__env, @__obj);
            @__return = global::net.sf.jni4net.utils.Convertor.StrongC2Jp<global::ASquared.SymbolicMath.Symbol>(@__env, @__real[row, col]);
            }catch (global::System.Exception __ex){@__env.ThrowExisting(__ex);}
            return @__return;
        }
        
        private static void Item10(global::System.IntPtr @__envp, global::net.sf.jni4net.utils.JniLocalHandle @__obj, int row, int col, global::net.sf.jni4net.utils.JniLocalHandle value) {
            // (IILasquared/symbolicmath/Symbol;)V
            // (IILASquared/SymbolicMath/Symbol;)V
            global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.Wrap(@__envp);
            try {
            global::ASquared.SymbolicMath.SymbolicMatrix @__real = global::net.sf.jni4net.utils.Convertor.StrongJp2C<global::ASquared.SymbolicMath.SymbolicMatrix>(@__env, @__obj);
            @__real[row, col] = global::net.sf.jni4net.utils.Convertor.StrongJp2C<global::ASquared.SymbolicMath.Symbol>(@__env, value);
            }catch (global::System.Exception __ex){@__env.ThrowExisting(__ex);}
        }
        
        private static global::net.sf.jni4net.utils.JniHandle Copy11(global::System.IntPtr @__envp, global::net.sf.jni4net.utils.JniLocalHandle @__obj) {
            // ()Lasquared/symbolicmath/SymbolicMatrix;
            // ()LASquared/SymbolicMath/SymbolicMatrix;
            global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.Wrap(@__envp);
            global::net.sf.jni4net.utils.JniHandle @__return = default(global::net.sf.jni4net.utils.JniHandle);
            try {
            global::ASquared.SymbolicMath.SymbolicMatrix @__real = global::net.sf.jni4net.utils.Convertor.StrongJp2C<global::ASquared.SymbolicMath.SymbolicMatrix>(@__env, @__obj);
            @__return = global::net.sf.jni4net.utils.Convertor.StrongC2Jp<global::ASquared.SymbolicMath.SymbolicMatrix>(@__env, @__real.Copy());
            }catch (global::System.Exception __ex){@__env.ThrowExisting(__ex);}
            return @__return;
        }
        
        private static global::net.sf.jni4net.utils.JniHandle ToArray12(global::System.IntPtr @__envp, global::net.sf.jni4net.utils.JniLocalHandle @__obj) {
            // ()[Lasquared/symbolicmath/Symbol;
            // ()[LASquared/SymbolicMath/Symbol;
            global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.Wrap(@__envp);
            global::net.sf.jni4net.utils.JniHandle @__return = default(global::net.sf.jni4net.utils.JniHandle);
            try {
            global::ASquared.SymbolicMath.SymbolicMatrix @__real = global::net.sf.jni4net.utils.Convertor.StrongJp2C<global::ASquared.SymbolicMath.SymbolicMatrix>(@__env, @__obj);
            @__return = global::net.sf.jni4net.utils.Convertor.ArrayStrongC2Jp<global::ASquared.SymbolicMath.Symbol[,], global::ASquared.SymbolicMath.Symbol>(@__env, @__real.ToArray());
            }catch (global::System.Exception __ex){@__env.ThrowExisting(__ex);}
            return @__return;
        }
        
        private static global::net.sf.jni4net.utils.JniHandle To1DArray13(global::System.IntPtr @__envp, global::net.sf.jni4net.utils.JniLocalHandle @__obj) {
            // ()[Lasquared/symbolicmath/Symbol;
            // ()[LASquared/SymbolicMath/Symbol;
            global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.Wrap(@__envp);
            global::net.sf.jni4net.utils.JniHandle @__return = default(global::net.sf.jni4net.utils.JniHandle);
            try {
            global::ASquared.SymbolicMath.SymbolicMatrix @__real = global::net.sf.jni4net.utils.Convertor.StrongJp2C<global::ASquared.SymbolicMath.SymbolicMatrix>(@__env, @__obj);
            @__return = global::net.sf.jni4net.utils.Convertor.ArrayStrongC2Jp<global::ASquared.SymbolicMath.Symbol[], global::ASquared.SymbolicMath.Symbol>(@__env, @__real.To1DArray());
            }catch (global::System.Exception __ex){@__env.ThrowExisting(__ex);}
            return @__return;
        }
        
        private static global::net.sf.jni4net.utils.JniHandle ConvertArray14(global::System.IntPtr @__envp, global::net.sf.jni4net.utils.JniLocalHandle @__class, global::net.sf.jni4net.utils.JniLocalHandle values, global::net.sf.jni4net.utils.JniLocalHandle orientation) {
            // ([Lasquared/symbolicmath/Symbol;Lasquared/symbolicmath/OrientationOption;)[Lasquared/symbolicmath/Symbol;
            // ([LASquared/SymbolicMath/Symbol;LASquared/SymbolicMath/OrientationOption;)[LASquared/SymbolicMath/Symbol;
            global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.Wrap(@__envp);
            global::net.sf.jni4net.utils.JniHandle @__return = default(global::net.sf.jni4net.utils.JniHandle);
            try {
            @__return = global::net.sf.jni4net.utils.Convertor.ArrayStrongC2Jp<global::ASquared.SymbolicMath.Symbol[,], global::ASquared.SymbolicMath.Symbol>(@__env, global::ASquared.SymbolicMath.SymbolicMatrix.ConvertArray(global::net.sf.jni4net.utils.Convertor.ArrayStrongJp2C<global::ASquared.SymbolicMath.Symbol[], global::ASquared.SymbolicMath.Symbol>(@__env, values), global::net.sf.jni4net.utils.Convertor.StrongJp2C<global::ASquared.SymbolicMath.OrientationOption>(@__env, orientation)));
            }catch (global::System.Exception __ex){@__env.ThrowExisting(__ex);}
            return @__return;
        }
        
        private static global::net.sf.jni4net.utils.JniHandle ConvertArrayToDataTable16(global::System.IntPtr @__envp, global::net.sf.jni4net.utils.JniLocalHandle @__class, global::net.sf.jni4net.utils.JniLocalHandle values, global::net.sf.jni4net.utils.JniLocalHandle orientation) {
            // ([Lasquared/symbolicmath/Symbol;Lasquared/symbolicmath/OrientationOption;)Lsystem/Object;
            // ([LASquared/SymbolicMath/Symbol;LASquared/SymbolicMath/OrientationOption;)LSystem/Data/DataTable;
            global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.Wrap(@__envp);
            global::net.sf.jni4net.utils.JniHandle @__return = default(global::net.sf.jni4net.utils.JniHandle);
            try {
            @__return = global::net.sf.jni4net.utils.Convertor.StrongC2Jp<global::System.Data.DataTable>(@__env, global::ASquared.SymbolicMath.SymbolicMatrix.ConvertArrayToDataTable(global::net.sf.jni4net.utils.Convertor.ArrayStrongJp2C<global::ASquared.SymbolicMath.Symbol[], global::ASquared.SymbolicMath.Symbol>(@__env, values), global::net.sf.jni4net.utils.Convertor.StrongJp2C<global::ASquared.SymbolicMath.OrientationOption>(@__env, orientation)));
            }catch (global::System.Exception __ex){@__env.ThrowExisting(__ex);}
            return @__return;
        }
        
        private static global::net.sf.jni4net.utils.JniHandle ConvertArrayToDataTable17(global::System.IntPtr @__envp, global::net.sf.jni4net.utils.JniLocalHandle @__class, global::net.sf.jni4net.utils.JniLocalHandle values) {
            // ([Lasquared/symbolicmath/Symbol;)Lsystem/Object;
            // ([LASquared/SymbolicMath/Symbol;)LSystem/Data/DataTable;
            global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.Wrap(@__envp);
            global::net.sf.jni4net.utils.JniHandle @__return = default(global::net.sf.jni4net.utils.JniHandle);
            try {
            @__return = global::net.sf.jni4net.utils.Convertor.StrongC2Jp<global::System.Data.DataTable>(@__env, global::ASquared.SymbolicMath.SymbolicMatrix.ConvertArrayToDataTable(global::net.sf.jni4net.utils.Convertor.ArrayStrongJp2C<global::ASquared.SymbolicMath.Symbol[,], global::ASquared.SymbolicMath.Symbol>(@__env, values)));
            }catch (global::System.Exception __ex){@__env.ThrowExisting(__ex);}
            return @__return;
        }
        
        private static global::net.sf.jni4net.utils.JniHandle BuildTable18(global::System.IntPtr @__envp, global::net.sf.jni4net.utils.JniLocalHandle @__class, int numRows, int numCols, global::net.sf.jni4net.utils.JniLocalHandle defaultValue) {
            // (IILasquared/symbolicmath/Symbol;)Lsystem/Object;
            // (IILASquared/SymbolicMath/Symbol;)LSystem/Data/DataTable;
            global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.Wrap(@__envp);
            global::net.sf.jni4net.utils.JniHandle @__return = default(global::net.sf.jni4net.utils.JniHandle);
            try {
            @__return = global::net.sf.jni4net.utils.Convertor.StrongC2Jp<global::System.Data.DataTable>(@__env, global::ASquared.SymbolicMath.SymbolicMatrix.BuildTable(numRows, numCols, global::net.sf.jni4net.utils.Convertor.StrongJp2C<global::ASquared.SymbolicMath.Symbol>(@__env, defaultValue)));
            }catch (global::System.Exception __ex){@__env.ThrowExisting(__ex);}
            return @__return;
        }
        
        private static global::net.sf.jni4net.utils.JniHandle FromArray19(global::System.IntPtr @__envp, global::net.sf.jni4net.utils.JniLocalHandle @__class, global::net.sf.jni4net.utils.JniLocalHandle values) {
            // ([Lasquared/symbolicmath/Symbol;)Lasquared/symbolicmath/SymbolicMatrix;
            // ([LASquared/SymbolicMath/Symbol;)LASquared/SymbolicMath/SymbolicMatrix;
            global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.Wrap(@__envp);
            global::net.sf.jni4net.utils.JniHandle @__return = default(global::net.sf.jni4net.utils.JniHandle);
            try {
            @__return = global::net.sf.jni4net.utils.Convertor.StrongC2Jp<global::ASquared.SymbolicMath.SymbolicMatrix>(@__env, global::ASquared.SymbolicMath.SymbolicMatrix.FromArray(global::net.sf.jni4net.utils.Convertor.ArrayStrongJp2C<global::ASquared.SymbolicMath.Symbol[,], global::ASquared.SymbolicMath.Symbol>(@__env, values)));
            }catch (global::System.Exception __ex){@__env.ThrowExisting(__ex);}
            return @__return;
        }
        
        private static void InsertRowsAt20(global::System.IntPtr @__envp, global::net.sf.jni4net.utils.JniLocalHandle @__obj, global::net.sf.jni4net.utils.JniLocalHandle newRows, int pos) {
            // (Lasquared/symbolicmath/SymbolicMatrix;I)V
            // (LASquared/SymbolicMath/SymbolicMatrix;I)V
            global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.Wrap(@__envp);
            try {
            global::ASquared.SymbolicMath.SymbolicMatrix @__real = global::net.sf.jni4net.utils.Convertor.StrongJp2C<global::ASquared.SymbolicMath.SymbolicMatrix>(@__env, @__obj);
            @__real.InsertRowsAt(global::net.sf.jni4net.utils.Convertor.StrongJp2C<global::ASquared.SymbolicMath.SymbolicMatrix>(@__env, newRows), pos);
            }catch (global::System.Exception __ex){@__env.ThrowExisting(__ex);}
        }
        
        private static void InsertColsAt21(global::System.IntPtr @__envp, global::net.sf.jni4net.utils.JniLocalHandle @__obj, global::net.sf.jni4net.utils.JniLocalHandle newCols, int pos) {
            // (Lasquared/symbolicmath/SymbolicMatrix;I)V
            // (LASquared/SymbolicMath/SymbolicMatrix;I)V
            global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.Wrap(@__envp);
            try {
            global::ASquared.SymbolicMath.SymbolicMatrix @__real = global::net.sf.jni4net.utils.Convertor.StrongJp2C<global::ASquared.SymbolicMath.SymbolicMatrix>(@__env, @__obj);
            @__real.InsertColsAt(global::net.sf.jni4net.utils.Convertor.StrongJp2C<global::ASquared.SymbolicMath.SymbolicMatrix>(@__env, newCols), pos);
            }catch (global::System.Exception __ex){@__env.ThrowExisting(__ex);}
        }
        
        private static void AppendRows22(global::System.IntPtr @__envp, global::net.sf.jni4net.utils.JniLocalHandle @__obj, global::net.sf.jni4net.utils.JniLocalHandle newRows) {
            // (Lasquared/symbolicmath/SymbolicMatrix;)V
            // (LASquared/SymbolicMath/SymbolicMatrix;)V
            global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.Wrap(@__envp);
            try {
            global::ASquared.SymbolicMath.SymbolicMatrix @__real = global::net.sf.jni4net.utils.Convertor.StrongJp2C<global::ASquared.SymbolicMath.SymbolicMatrix>(@__env, @__obj);
            @__real.AppendRows(global::net.sf.jni4net.utils.Convertor.StrongJp2C<global::ASquared.SymbolicMath.SymbolicMatrix>(@__env, newRows));
            }catch (global::System.Exception __ex){@__env.ThrowExisting(__ex);}
        }
        
        private static void AppendRows23(global::System.IntPtr @__envp, global::net.sf.jni4net.utils.JniLocalHandle @__obj, int numRows) {
            // (I)V
            // (I)V
            global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.Wrap(@__envp);
            try {
            global::ASquared.SymbolicMath.SymbolicMatrix @__real = global::net.sf.jni4net.utils.Convertor.StrongJp2C<global::ASquared.SymbolicMath.SymbolicMatrix>(@__env, @__obj);
            @__real.AppendRows(numRows);
            }catch (global::System.Exception __ex){@__env.ThrowExisting(__ex);}
        }
        
        private static void AppendCols24(global::System.IntPtr @__envp, global::net.sf.jni4net.utils.JniLocalHandle @__obj, global::net.sf.jni4net.utils.JniLocalHandle newCols) {
            // (Lasquared/symbolicmath/SymbolicMatrix;)V
            // (LASquared/SymbolicMath/SymbolicMatrix;)V
            global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.Wrap(@__envp);
            try {
            global::ASquared.SymbolicMath.SymbolicMatrix @__real = global::net.sf.jni4net.utils.Convertor.StrongJp2C<global::ASquared.SymbolicMath.SymbolicMatrix>(@__env, @__obj);
            @__real.AppendCols(global::net.sf.jni4net.utils.Convertor.StrongJp2C<global::ASquared.SymbolicMath.SymbolicMatrix>(@__env, newCols));
            }catch (global::System.Exception __ex){@__env.ThrowExisting(__ex);}
        }
        
        private static void AppendCols25(global::System.IntPtr @__envp, global::net.sf.jni4net.utils.JniLocalHandle @__obj, int numCols) {
            // (I)V
            // (I)V
            global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.Wrap(@__envp);
            try {
            global::ASquared.SymbolicMath.SymbolicMatrix @__real = global::net.sf.jni4net.utils.Convertor.StrongJp2C<global::ASquared.SymbolicMath.SymbolicMatrix>(@__env, @__obj);
            @__real.AppendCols(numCols);
            }catch (global::System.Exception __ex){@__env.ThrowExisting(__ex);}
        }
        
        private static global::net.sf.jni4net.utils.JniHandle RemoveRowAt26(global::System.IntPtr @__envp, global::net.sf.jni4net.utils.JniLocalHandle @__obj, int pos) {
            // (I)Lasquared/symbolicmath/SymbolicMatrix;
            // (I)LASquared/SymbolicMath/SymbolicMatrix;
            global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.Wrap(@__envp);
            global::net.sf.jni4net.utils.JniHandle @__return = default(global::net.sf.jni4net.utils.JniHandle);
            try {
            global::ASquared.SymbolicMath.SymbolicMatrix @__real = global::net.sf.jni4net.utils.Convertor.StrongJp2C<global::ASquared.SymbolicMath.SymbolicMatrix>(@__env, @__obj);
            @__return = global::net.sf.jni4net.utils.Convertor.StrongC2Jp<global::ASquared.SymbolicMath.SymbolicMatrix>(@__env, @__real.RemoveRowAt(pos));
            }catch (global::System.Exception __ex){@__env.ThrowExisting(__ex);}
            return @__return;
        }
        
        private static global::net.sf.jni4net.utils.JniHandle RemoveColAt27(global::System.IntPtr @__envp, global::net.sf.jni4net.utils.JniLocalHandle @__obj, int pos) {
            // (I)Lasquared/symbolicmath/SymbolicMatrix;
            // (I)LASquared/SymbolicMath/SymbolicMatrix;
            global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.Wrap(@__envp);
            global::net.sf.jni4net.utils.JniHandle @__return = default(global::net.sf.jni4net.utils.JniHandle);
            try {
            global::ASquared.SymbolicMath.SymbolicMatrix @__real = global::net.sf.jni4net.utils.Convertor.StrongJp2C<global::ASquared.SymbolicMath.SymbolicMatrix>(@__env, @__obj);
            @__return = global::net.sf.jni4net.utils.Convertor.StrongC2Jp<global::ASquared.SymbolicMath.SymbolicMatrix>(@__env, @__real.RemoveColAt(pos));
            }catch (global::System.Exception __ex){@__env.ThrowExisting(__ex);}
            return @__return;
        }
        
        private static void MoveRow28(global::System.IntPtr @__envp, global::net.sf.jni4net.utils.JniLocalHandle @__obj, int fromPos, int toPos) {
            // (II)V
            // (II)V
            global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.Wrap(@__envp);
            try {
            global::ASquared.SymbolicMath.SymbolicMatrix @__real = global::net.sf.jni4net.utils.Convertor.StrongJp2C<global::ASquared.SymbolicMath.SymbolicMatrix>(@__env, @__obj);
            @__real.MoveRow(fromPos, toPos);
            }catch (global::System.Exception __ex){@__env.ThrowExisting(__ex);}
        }
        
        private static void MoveCol29(global::System.IntPtr @__envp, global::net.sf.jni4net.utils.JniLocalHandle @__obj, int fromPos, int toPos) {
            // (II)V
            // (II)V
            global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.Wrap(@__envp);
            try {
            global::ASquared.SymbolicMath.SymbolicMatrix @__real = global::net.sf.jni4net.utils.Convertor.StrongJp2C<global::ASquared.SymbolicMath.SymbolicMatrix>(@__env, @__obj);
            @__real.MoveCol(fromPos, toPos);
            }catch (global::System.Exception __ex){@__env.ThrowExisting(__ex);}
        }
        
        private static void ReplaceRow30(global::System.IntPtr @__envp, global::net.sf.jni4net.utils.JniLocalHandle @__obj, int pos, global::net.sf.jni4net.utils.JniLocalHandle values) {
            // (ILasquared/symbolicmath/SymbolicMatrix;)V
            // (ILASquared/SymbolicMath/SymbolicMatrix;)V
            global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.Wrap(@__envp);
            try {
            global::ASquared.SymbolicMath.SymbolicMatrix @__real = global::net.sf.jni4net.utils.Convertor.StrongJp2C<global::ASquared.SymbolicMath.SymbolicMatrix>(@__env, @__obj);
            @__real.ReplaceRow(pos, global::net.sf.jni4net.utils.Convertor.StrongJp2C<global::ASquared.SymbolicMath.SymbolicMatrix>(@__env, values));
            }catch (global::System.Exception __ex){@__env.ThrowExisting(__ex);}
        }
        
        private static void ReplaceCol31(global::System.IntPtr @__envp, global::net.sf.jni4net.utils.JniLocalHandle @__obj, int pos, global::net.sf.jni4net.utils.JniLocalHandle values) {
            // (ILasquared/symbolicmath/SymbolicMatrix;)V
            // (ILASquared/SymbolicMath/SymbolicMatrix;)V
            global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.Wrap(@__envp);
            try {
            global::ASquared.SymbolicMath.SymbolicMatrix @__real = global::net.sf.jni4net.utils.Convertor.StrongJp2C<global::ASquared.SymbolicMath.SymbolicMatrix>(@__env, @__obj);
            @__real.ReplaceCol(pos, global::net.sf.jni4net.utils.Convertor.StrongJp2C<global::ASquared.SymbolicMath.SymbolicMatrix>(@__env, values));
            }catch (global::System.Exception __ex){@__env.ThrowExisting(__ex);}
        }
        
        private static global::net.sf.jni4net.utils.JniHandle GetRow32(global::System.IntPtr @__envp, global::net.sf.jni4net.utils.JniLocalHandle @__obj, int pos) {
            // (I)Lasquared/symbolicmath/SymbolicMatrix;
            // (I)LASquared/SymbolicMath/SymbolicMatrix;
            global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.Wrap(@__envp);
            global::net.sf.jni4net.utils.JniHandle @__return = default(global::net.sf.jni4net.utils.JniHandle);
            try {
            global::ASquared.SymbolicMath.SymbolicMatrix @__real = global::net.sf.jni4net.utils.Convertor.StrongJp2C<global::ASquared.SymbolicMath.SymbolicMatrix>(@__env, @__obj);
            @__return = global::net.sf.jni4net.utils.Convertor.StrongC2Jp<global::ASquared.SymbolicMath.SymbolicMatrix>(@__env, @__real.GetRow(pos));
            }catch (global::System.Exception __ex){@__env.ThrowExisting(__ex);}
            return @__return;
        }
        
        private static global::net.sf.jni4net.utils.JniHandle GetCol33(global::System.IntPtr @__envp, global::net.sf.jni4net.utils.JniLocalHandle @__obj, int pos) {
            // (I)Lasquared/symbolicmath/SymbolicMatrix;
            // (I)LASquared/SymbolicMath/SymbolicMatrix;
            global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.Wrap(@__envp);
            global::net.sf.jni4net.utils.JniHandle @__return = default(global::net.sf.jni4net.utils.JniHandle);
            try {
            global::ASquared.SymbolicMath.SymbolicMatrix @__real = global::net.sf.jni4net.utils.Convertor.StrongJp2C<global::ASquared.SymbolicMath.SymbolicMatrix>(@__env, @__obj);
            @__return = global::net.sf.jni4net.utils.Convertor.StrongC2Jp<global::ASquared.SymbolicMath.SymbolicMatrix>(@__env, @__real.GetCol(pos));
            }catch (global::System.Exception __ex){@__env.ThrowExisting(__ex);}
            return @__return;
        }
        
        private static global::net.sf.jni4net.utils.JniHandle GetRows34(global::System.IntPtr @__envp, global::net.sf.jni4net.utils.JniLocalHandle @__obj, global::net.sf.jni4net.utils.JniLocalHandle pos) {
            // ([I)Lasquared/symbolicmath/SymbolicMatrix;
            // ([I)LASquared/SymbolicMath/SymbolicMatrix;
            global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.Wrap(@__envp);
            global::net.sf.jni4net.utils.JniHandle @__return = default(global::net.sf.jni4net.utils.JniHandle);
            try {
            global::ASquared.SymbolicMath.SymbolicMatrix @__real = global::net.sf.jni4net.utils.Convertor.StrongJp2C<global::ASquared.SymbolicMath.SymbolicMatrix>(@__env, @__obj);
            @__return = global::net.sf.jni4net.utils.Convertor.StrongC2Jp<global::ASquared.SymbolicMath.SymbolicMatrix>(@__env, @__real.GetRows(global::net.sf.jni4net.utils.Convertor.ArrayPrimJ2Cint(@__env, pos)));
            }catch (global::System.Exception __ex){@__env.ThrowExisting(__ex);}
            return @__return;
        }
        
        private static global::net.sf.jni4net.utils.JniHandle GetCols35(global::System.IntPtr @__envp, global::net.sf.jni4net.utils.JniLocalHandle @__obj, global::net.sf.jni4net.utils.JniLocalHandle pos) {
            // ([I)Lasquared/symbolicmath/SymbolicMatrix;
            // ([I)LASquared/SymbolicMath/SymbolicMatrix;
            global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.Wrap(@__envp);
            global::net.sf.jni4net.utils.JniHandle @__return = default(global::net.sf.jni4net.utils.JniHandle);
            try {
            global::ASquared.SymbolicMath.SymbolicMatrix @__real = global::net.sf.jni4net.utils.Convertor.StrongJp2C<global::ASquared.SymbolicMath.SymbolicMatrix>(@__env, @__obj);
            @__return = global::net.sf.jni4net.utils.Convertor.StrongC2Jp<global::ASquared.SymbolicMath.SymbolicMatrix>(@__env, @__real.GetCols(global::net.sf.jni4net.utils.Convertor.ArrayPrimJ2Cint(@__env, pos)));
            }catch (global::System.Exception __ex){@__env.ThrowExisting(__ex);}
            return @__return;
        }
        
        private static global::net.sf.jni4net.utils.JniHandle GetRows36(global::System.IntPtr @__envp, global::net.sf.jni4net.utils.JniLocalHandle @__obj, int fromPos, int toPos) {
            // (II)Lasquared/symbolicmath/SymbolicMatrix;
            // (II)LASquared/SymbolicMath/SymbolicMatrix;
            global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.Wrap(@__envp);
            global::net.sf.jni4net.utils.JniHandle @__return = default(global::net.sf.jni4net.utils.JniHandle);
            try {
            global::ASquared.SymbolicMath.SymbolicMatrix @__real = global::net.sf.jni4net.utils.Convertor.StrongJp2C<global::ASquared.SymbolicMath.SymbolicMatrix>(@__env, @__obj);
            @__return = global::net.sf.jni4net.utils.Convertor.StrongC2Jp<global::ASquared.SymbolicMath.SymbolicMatrix>(@__env, @__real.GetRows(fromPos, toPos));
            }catch (global::System.Exception __ex){@__env.ThrowExisting(__ex);}
            return @__return;
        }
        
        private static global::net.sf.jni4net.utils.JniHandle GetCols37(global::System.IntPtr @__envp, global::net.sf.jni4net.utils.JniLocalHandle @__obj, int fromPos, int toPos) {
            // (II)Lasquared/symbolicmath/SymbolicMatrix;
            // (II)LASquared/SymbolicMath/SymbolicMatrix;
            global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.Wrap(@__envp);
            global::net.sf.jni4net.utils.JniHandle @__return = default(global::net.sf.jni4net.utils.JniHandle);
            try {
            global::ASquared.SymbolicMath.SymbolicMatrix @__real = global::net.sf.jni4net.utils.Convertor.StrongJp2C<global::ASquared.SymbolicMath.SymbolicMatrix>(@__env, @__obj);
            @__return = global::net.sf.jni4net.utils.Convertor.StrongC2Jp<global::ASquared.SymbolicMath.SymbolicMatrix>(@__env, @__real.GetCols(fromPos, toPos));
            }catch (global::System.Exception __ex){@__env.ThrowExisting(__ex);}
            return @__return;
        }
        
        private static global::net.sf.jni4net.utils.JniHandle GetRowArray38(global::System.IntPtr @__envp, global::net.sf.jni4net.utils.JniLocalHandle @__obj, int pos) {
            // (I)[Lasquared/symbolicmath/Symbol;
            // (I)[LASquared/SymbolicMath/Symbol;
            global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.Wrap(@__envp);
            global::net.sf.jni4net.utils.JniHandle @__return = default(global::net.sf.jni4net.utils.JniHandle);
            try {
            global::ASquared.SymbolicMath.SymbolicMatrix @__real = global::net.sf.jni4net.utils.Convertor.StrongJp2C<global::ASquared.SymbolicMath.SymbolicMatrix>(@__env, @__obj);
            @__return = global::net.sf.jni4net.utils.Convertor.ArrayStrongC2Jp<global::ASquared.SymbolicMath.Symbol[], global::ASquared.SymbolicMath.Symbol>(@__env, @__real.GetRowArray(pos));
            }catch (global::System.Exception __ex){@__env.ThrowExisting(__ex);}
            return @__return;
        }
        
        private static global::net.sf.jni4net.utils.JniHandle GetColArray39(global::System.IntPtr @__envp, global::net.sf.jni4net.utils.JniLocalHandle @__obj, int pos) {
            // (I)[Lasquared/symbolicmath/Symbol;
            // (I)[LASquared/SymbolicMath/Symbol;
            global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.Wrap(@__envp);
            global::net.sf.jni4net.utils.JniHandle @__return = default(global::net.sf.jni4net.utils.JniHandle);
            try {
            global::ASquared.SymbolicMath.SymbolicMatrix @__real = global::net.sf.jni4net.utils.Convertor.StrongJp2C<global::ASquared.SymbolicMath.SymbolicMatrix>(@__env, @__obj);
            @__return = global::net.sf.jni4net.utils.Convertor.ArrayStrongC2Jp<global::ASquared.SymbolicMath.Symbol[], global::ASquared.SymbolicMath.Symbol>(@__env, @__real.GetColArray(pos));
            }catch (global::System.Exception __ex){@__env.ThrowExisting(__ex);}
            return @__return;
        }
        
        private static global::net.sf.jni4net.utils.JniHandle Add40(global::System.IntPtr @__envp, global::net.sf.jni4net.utils.JniLocalHandle @__obj, global::net.sf.jni4net.utils.JniLocalHandle m) {
            // (Lasquared/symbolicmath/SymbolicMatrix;)Lasquared/symbolicmath/SymbolicMatrix;
            // (LASquared/SymbolicMath/SymbolicMatrix;)LASquared/SymbolicMath/SymbolicMatrix;
            global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.Wrap(@__envp);
            global::net.sf.jni4net.utils.JniHandle @__return = default(global::net.sf.jni4net.utils.JniHandle);
            try {
            global::ASquared.SymbolicMath.SymbolicMatrix @__real = global::net.sf.jni4net.utils.Convertor.StrongJp2C<global::ASquared.SymbolicMath.SymbolicMatrix>(@__env, @__obj);
            @__return = global::net.sf.jni4net.utils.Convertor.StrongC2Jp<global::ASquared.SymbolicMath.SymbolicMatrix>(@__env, @__real.Add(global::net.sf.jni4net.utils.Convertor.StrongJp2C<global::ASquared.SymbolicMath.SymbolicMatrix>(@__env, m)));
            }catch (global::System.Exception __ex){@__env.ThrowExisting(__ex);}
            return @__return;
        }
        
        private static global::net.sf.jni4net.utils.JniHandle Add41(global::System.IntPtr @__envp, global::net.sf.jni4net.utils.JniLocalHandle @__obj, global::net.sf.jni4net.utils.JniLocalHandle val) {
            // (Lasquared/symbolicmath/Symbol;)Lasquared/symbolicmath/SymbolicMatrix;
            // (LASquared/SymbolicMath/Symbol;)LASquared/SymbolicMath/SymbolicMatrix;
            global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.Wrap(@__envp);
            global::net.sf.jni4net.utils.JniHandle @__return = default(global::net.sf.jni4net.utils.JniHandle);
            try {
            global::ASquared.SymbolicMath.SymbolicMatrix @__real = global::net.sf.jni4net.utils.Convertor.StrongJp2C<global::ASquared.SymbolicMath.SymbolicMatrix>(@__env, @__obj);
            @__return = global::net.sf.jni4net.utils.Convertor.StrongC2Jp<global::ASquared.SymbolicMath.SymbolicMatrix>(@__env, @__real.Add(global::net.sf.jni4net.utils.Convertor.StrongJp2C<global::ASquared.SymbolicMath.Symbol>(@__env, val)));
            }catch (global::System.Exception __ex){@__env.ThrowExisting(__ex);}
            return @__return;
        }
        
        private static global::net.sf.jni4net.utils.JniHandle Mult42(global::System.IntPtr @__envp, global::net.sf.jni4net.utils.JniLocalHandle @__obj, global::net.sf.jni4net.utils.JniLocalHandle scalar) {
            // (Lasquared/symbolicmath/Symbol;)Lasquared/symbolicmath/SymbolicMatrix;
            // (LASquared/SymbolicMath/Symbol;)LASquared/SymbolicMath/SymbolicMatrix;
            global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.Wrap(@__envp);
            global::net.sf.jni4net.utils.JniHandle @__return = default(global::net.sf.jni4net.utils.JniHandle);
            try {
            global::ASquared.SymbolicMath.SymbolicMatrix @__real = global::net.sf.jni4net.utils.Convertor.StrongJp2C<global::ASquared.SymbolicMath.SymbolicMatrix>(@__env, @__obj);
            @__return = global::net.sf.jni4net.utils.Convertor.StrongC2Jp<global::ASquared.SymbolicMath.SymbolicMatrix>(@__env, @__real.Mult(global::net.sf.jni4net.utils.Convertor.StrongJp2C<global::ASquared.SymbolicMath.Symbol>(@__env, scalar)));
            }catch (global::System.Exception __ex){@__env.ThrowExisting(__ex);}
            return @__return;
        }
        
        private static global::net.sf.jni4net.utils.JniHandle Mult43(global::System.IntPtr @__envp, global::net.sf.jni4net.utils.JniLocalHandle @__obj, global::net.sf.jni4net.utils.JniLocalHandle m, global::net.sf.jni4net.utils.JniLocalHandle tOpt) {
            // (Lasquared/symbolicmath/SymbolicMatrix;Lasquared/TransposeOption;)Lasquared/symbolicmath/SymbolicMatrix;
            // (LASquared/SymbolicMath/SymbolicMatrix;LASquared/TransposeOption;)LASquared/SymbolicMath/SymbolicMatrix;
            global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.Wrap(@__envp);
            global::net.sf.jni4net.utils.JniHandle @__return = default(global::net.sf.jni4net.utils.JniHandle);
            try {
            global::ASquared.SymbolicMath.SymbolicMatrix @__real = global::net.sf.jni4net.utils.Convertor.StrongJp2C<global::ASquared.SymbolicMath.SymbolicMatrix>(@__env, @__obj);
            @__return = global::net.sf.jni4net.utils.Convertor.StrongC2Jp<global::ASquared.SymbolicMath.SymbolicMatrix>(@__env, @__real.Mult(global::net.sf.jni4net.utils.Convertor.StrongJp2C<global::ASquared.SymbolicMath.SymbolicMatrix>(@__env, m), global::net.sf.jni4net.utils.Convertor.StrongJp2C<global::ASquared.TransposeOption>(@__env, tOpt)));
            }catch (global::System.Exception __ex){@__env.ThrowExisting(__ex);}
            return @__return;
        }
        
        private static global::net.sf.jni4net.utils.JniHandle ElementwiseMult44(global::System.IntPtr @__envp, global::net.sf.jni4net.utils.JniLocalHandle @__obj, global::net.sf.jni4net.utils.JniLocalHandle m) {
            // (Lasquared/symbolicmath/SymbolicMatrix;)Lasquared/symbolicmath/SymbolicMatrix;
            // (LASquared/SymbolicMath/SymbolicMatrix;)LASquared/SymbolicMath/SymbolicMatrix;
            global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.Wrap(@__envp);
            global::net.sf.jni4net.utils.JniHandle @__return = default(global::net.sf.jni4net.utils.JniHandle);
            try {
            global::ASquared.SymbolicMath.SymbolicMatrix @__real = global::net.sf.jni4net.utils.Convertor.StrongJp2C<global::ASquared.SymbolicMath.SymbolicMatrix>(@__env, @__obj);
            @__return = global::net.sf.jni4net.utils.Convertor.StrongC2Jp<global::ASquared.SymbolicMath.SymbolicMatrix>(@__env, @__real.ElementwiseMult(global::net.sf.jni4net.utils.Convertor.StrongJp2C<global::ASquared.SymbolicMath.SymbolicMatrix>(@__env, m)));
            }catch (global::System.Exception __ex){@__env.ThrowExisting(__ex);}
            return @__return;
        }
        
        private static global::net.sf.jni4net.utils.JniHandle ElementwiseDivide45(global::System.IntPtr @__envp, global::net.sf.jni4net.utils.JniLocalHandle @__obj, global::net.sf.jni4net.utils.JniLocalHandle m) {
            // (Lasquared/symbolicmath/SymbolicMatrix;)Lasquared/symbolicmath/SymbolicMatrix;
            // (LASquared/SymbolicMath/SymbolicMatrix;)LASquared/SymbolicMath/SymbolicMatrix;
            global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.Wrap(@__envp);
            global::net.sf.jni4net.utils.JniHandle @__return = default(global::net.sf.jni4net.utils.JniHandle);
            try {
            global::ASquared.SymbolicMath.SymbolicMatrix @__real = global::net.sf.jni4net.utils.Convertor.StrongJp2C<global::ASquared.SymbolicMath.SymbolicMatrix>(@__env, @__obj);
            @__return = global::net.sf.jni4net.utils.Convertor.StrongC2Jp<global::ASquared.SymbolicMath.SymbolicMatrix>(@__env, @__real.ElementwiseDivide(global::net.sf.jni4net.utils.Convertor.StrongJp2C<global::ASquared.SymbolicMath.SymbolicMatrix>(@__env, m)));
            }catch (global::System.Exception __ex){@__env.ThrowExisting(__ex);}
            return @__return;
        }
        
        private static global::net.sf.jni4net.utils.JniHandle Pow46(global::System.IntPtr @__envp, global::net.sf.jni4net.utils.JniLocalHandle @__obj, int b) {
            // (I)Lasquared/symbolicmath/SymbolicMatrix;
            // (I)LASquared/SymbolicMath/SymbolicMatrix;
            global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.Wrap(@__envp);
            global::net.sf.jni4net.utils.JniHandle @__return = default(global::net.sf.jni4net.utils.JniHandle);
            try {
            global::ASquared.SymbolicMath.SymbolicMatrix @__real = global::net.sf.jni4net.utils.Convertor.StrongJp2C<global::ASquared.SymbolicMath.SymbolicMatrix>(@__env, @__obj);
            @__return = global::net.sf.jni4net.utils.Convertor.StrongC2Jp<global::ASquared.SymbolicMath.SymbolicMatrix>(@__env, @__real.Pow(b));
            }catch (global::System.Exception __ex){@__env.ThrowExisting(__ex);}
            return @__return;
        }
        
        private static global::net.sf.jni4net.utils.JniHandle Transpose47(global::System.IntPtr @__envp, global::net.sf.jni4net.utils.JniLocalHandle @__obj) {
            // ()Lasquared/symbolicmath/SymbolicMatrix;
            // ()LASquared/SymbolicMath/SymbolicMatrix;
            global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.Wrap(@__envp);
            global::net.sf.jni4net.utils.JniHandle @__return = default(global::net.sf.jni4net.utils.JniHandle);
            try {
            global::ASquared.SymbolicMath.SymbolicMatrix @__real = global::net.sf.jni4net.utils.Convertor.StrongJp2C<global::ASquared.SymbolicMath.SymbolicMatrix>(@__env, @__obj);
            @__return = global::net.sf.jni4net.utils.Convertor.StrongC2Jp<global::ASquared.SymbolicMath.SymbolicMatrix>(@__env, @__real.Transpose());
            }catch (global::System.Exception __ex){@__env.ThrowExisting(__ex);}
            return @__return;
        }
        
        private static void Pivot48(global::System.IntPtr @__envp, global::net.sf.jni4net.utils.JniLocalHandle @__obj, int row, int col) {
            // (II)V
            // (II)V
            global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.Wrap(@__envp);
            try {
            global::ASquared.SymbolicMath.SymbolicMatrix @__real = global::net.sf.jni4net.utils.Convertor.StrongJp2C<global::ASquared.SymbolicMath.SymbolicMatrix>(@__env, @__obj);
            @__real.Pivot(row, col);
            }catch (global::System.Exception __ex){@__env.ThrowExisting(__ex);}
        }
        
        private static void RREF49(global::System.IntPtr @__envp, global::net.sf.jni4net.utils.JniLocalHandle @__obj) {
            // ()V
            // ()V
            global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.Wrap(@__envp);
            try {
            global::ASquared.SymbolicMath.SymbolicMatrix @__real = global::net.sf.jni4net.utils.Convertor.StrongJp2C<global::ASquared.SymbolicMath.SymbolicMatrix>(@__env, @__obj);
            @__real.RREF();
            }catch (global::System.Exception __ex){@__env.ThrowExisting(__ex);}
        }
        
        private static global::net.sf.jni4net.utils.JniHandle Inverse50(global::System.IntPtr @__envp, global::net.sf.jni4net.utils.JniLocalHandle @__obj) {
            // ()Lasquared/symbolicmath/SymbolicMatrix;
            // ()LASquared/SymbolicMath/SymbolicMatrix;
            global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.Wrap(@__envp);
            global::net.sf.jni4net.utils.JniHandle @__return = default(global::net.sf.jni4net.utils.JniHandle);
            try {
            global::ASquared.SymbolicMath.SymbolicMatrix @__real = global::net.sf.jni4net.utils.Convertor.StrongJp2C<global::ASquared.SymbolicMath.SymbolicMatrix>(@__env, @__obj);
            @__return = global::net.sf.jni4net.utils.Convertor.StrongC2Jp<global::ASquared.SymbolicMath.SymbolicMatrix>(@__env, @__real.Inverse());
            }catch (global::System.Exception __ex){@__env.ThrowExisting(__ex);}
            return @__return;
        }
        
        private static global::net.sf.jni4net.utils.JniHandle SolveLinearSys51(global::System.IntPtr @__envp, global::net.sf.jni4net.utils.JniLocalHandle @__class, global::net.sf.jni4net.utils.JniLocalHandle A, global::net.sf.jni4net.utils.JniLocalHandle b) {
            // (Lasquared/symbolicmath/SymbolicMatrix;Lasquared/symbolicmath/SymbolicMatrix;)Lasquared/symbolicmath/SymbolicMatrix;
            // (LASquared/SymbolicMath/SymbolicMatrix;LASquared/SymbolicMath/SymbolicMatrix;)LASquared/SymbolicMath/SymbolicMatrix;
            global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.Wrap(@__envp);
            global::net.sf.jni4net.utils.JniHandle @__return = default(global::net.sf.jni4net.utils.JniHandle);
            try {
            @__return = global::net.sf.jni4net.utils.Convertor.StrongC2Jp<global::ASquared.SymbolicMath.SymbolicMatrix>(@__env, global::ASquared.SymbolicMath.SymbolicMatrix.SolveLinearSys(global::net.sf.jni4net.utils.Convertor.StrongJp2C<global::ASquared.SymbolicMath.SymbolicMatrix>(@__env, A), global::net.sf.jni4net.utils.Convertor.StrongJp2C<global::ASquared.SymbolicMath.SymbolicMatrix>(@__env, b)));
            }catch (global::System.Exception __ex){@__env.ThrowExisting(__ex);}
            return @__return;
        }
        
        private static global::net.sf.jni4net.utils.JniHandle FromString52(global::System.IntPtr @__envp, global::net.sf.jni4net.utils.JniLocalHandle @__class, global::net.sf.jni4net.utils.JniLocalHandle matrix) {
            // (Ljava/lang/String;)Lasquared/symbolicmath/SymbolicMatrix;
            // (LSystem/String;)LASquared/SymbolicMath/SymbolicMatrix;
            global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.Wrap(@__envp);
            global::net.sf.jni4net.utils.JniHandle @__return = default(global::net.sf.jni4net.utils.JniHandle);
            try {
            @__return = global::net.sf.jni4net.utils.Convertor.StrongC2Jp<global::ASquared.SymbolicMath.SymbolicMatrix>(@__env, global::ASquared.SymbolicMath.SymbolicMatrix.FromString(global::net.sf.jni4net.utils.Convertor.StrongJ2CString(@__env, matrix)));
            }catch (global::System.Exception __ex){@__env.ThrowExisting(__ex);}
            return @__return;
        }
        
        private static global::net.sf.jni4net.utils.JniHandle Identity53(global::System.IntPtr @__envp, global::net.sf.jni4net.utils.JniLocalHandle @__class, int n) {
            // (I)Lasquared/symbolicmath/SymbolicMatrix;
            // (I)LASquared/SymbolicMath/SymbolicMatrix;
            global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.Wrap(@__envp);
            global::net.sf.jni4net.utils.JniHandle @__return = default(global::net.sf.jni4net.utils.JniHandle);
            try {
            @__return = global::net.sf.jni4net.utils.Convertor.StrongC2Jp<global::ASquared.SymbolicMath.SymbolicMatrix>(@__env, global::ASquared.SymbolicMath.SymbolicMatrix.Identity(n));
            }catch (global::System.Exception __ex){@__env.ThrowExisting(__ex);}
            return @__return;
        }
        
        private static void @__ctorSymbolicMatrix0(global::System.IntPtr @__envp, global::net.sf.jni4net.utils.JniLocalHandle @__class, global::net.sf.jni4net.utils.JniLocalHandle @__obj, int numRows) {
            // (I)V
            // (I)V
            global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.Wrap(@__envp);
            try {
            global::ASquared.SymbolicMath.SymbolicMatrix @__real = new global::ASquared.SymbolicMath.SymbolicMatrix(numRows);
            global::net.sf.jni4net.utils.Convertor.InitProxy(@__env, @__obj, @__real);
            }catch (global::System.Exception __ex){@__env.ThrowExisting(__ex);}
        }
        
        private static void @__ctorSymbolicMatrix1(global::System.IntPtr @__envp, global::net.sf.jni4net.utils.JniLocalHandle @__class, global::net.sf.jni4net.utils.JniLocalHandle @__obj, int numRows, global::net.sf.jni4net.utils.JniLocalHandle defaultValue) {
            // (ILasquared/symbolicmath/Symbol;)V
            // (ILASquared/SymbolicMath/Symbol;)V
            global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.Wrap(@__envp);
            try {
            global::ASquared.SymbolicMath.SymbolicMatrix @__real = new global::ASquared.SymbolicMath.SymbolicMatrix(numRows, global::net.sf.jni4net.utils.Convertor.StrongJp2C<global::ASquared.SymbolicMath.Symbol>(@__env, defaultValue));
            global::net.sf.jni4net.utils.Convertor.InitProxy(@__env, @__obj, @__real);
            }catch (global::System.Exception __ex){@__env.ThrowExisting(__ex);}
        }
        
        private static void @__ctorSymbolicMatrix2(global::System.IntPtr @__envp, global::net.sf.jni4net.utils.JniLocalHandle @__class, global::net.sf.jni4net.utils.JniLocalHandle @__obj, int numRows, int numCols) {
            // (II)V
            // (II)V
            global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.Wrap(@__envp);
            try {
            global::ASquared.SymbolicMath.SymbolicMatrix @__real = new global::ASquared.SymbolicMath.SymbolicMatrix(numRows, numCols);
            global::net.sf.jni4net.utils.Convertor.InitProxy(@__env, @__obj, @__real);
            }catch (global::System.Exception __ex){@__env.ThrowExisting(__ex);}
        }
        
        private static void @__ctorSymbolicMatrix3(global::System.IntPtr @__envp, global::net.sf.jni4net.utils.JniLocalHandle @__class, global::net.sf.jni4net.utils.JniLocalHandle @__obj, int numRows, int numCols, global::net.sf.jni4net.utils.JniLocalHandle defaultValue) {
            // (IILasquared/symbolicmath/Symbol;)V
            // (IILASquared/SymbolicMath/Symbol;)V
            global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.Wrap(@__envp);
            try {
            global::ASquared.SymbolicMath.SymbolicMatrix @__real = new global::ASquared.SymbolicMath.SymbolicMatrix(numRows, numCols, global::net.sf.jni4net.utils.Convertor.StrongJp2C<global::ASquared.SymbolicMath.Symbol>(@__env, defaultValue));
            global::net.sf.jni4net.utils.Convertor.InitProxy(@__env, @__obj, @__real);
            }catch (global::System.Exception __ex){@__env.ThrowExisting(__ex);}
        }
        
        private static void @__ctorSymbolicMatrix4(global::System.IntPtr @__envp, global::net.sf.jni4net.utils.JniLocalHandle @__class, global::net.sf.jni4net.utils.JniLocalHandle @__obj, global::net.sf.jni4net.utils.JniLocalHandle values) {
            // ([Lasquared/symbolicmath/Symbol;)V
            // ([LASquared/SymbolicMath/Symbol;)V
            global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.Wrap(@__envp);
            try {
            global::ASquared.SymbolicMath.SymbolicMatrix @__real = new global::ASquared.SymbolicMath.SymbolicMatrix(global::net.sf.jni4net.utils.Convertor.ArrayStrongJp2C<global::ASquared.SymbolicMath.Symbol[], global::ASquared.SymbolicMath.Symbol>(@__env, values));
            global::net.sf.jni4net.utils.Convertor.InitProxy(@__env, @__obj, @__real);
            }catch (global::System.Exception __ex){@__env.ThrowExisting(__ex);}
        }
        
        private static void @__ctorSymbolicMatrix5(global::System.IntPtr @__envp, global::net.sf.jni4net.utils.JniLocalHandle @__class, global::net.sf.jni4net.utils.JniLocalHandle @__obj, global::net.sf.jni4net.utils.JniLocalHandle values, global::net.sf.jni4net.utils.JniLocalHandle orientation) {
            // ([Lasquared/symbolicmath/Symbol;Lasquared/symbolicmath/OrientationOption;)V
            // ([LASquared/SymbolicMath/Symbol;LASquared/SymbolicMath/OrientationOption;)V
            global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.Wrap(@__envp);
            try {
            global::ASquared.SymbolicMath.SymbolicMatrix @__real = new global::ASquared.SymbolicMath.SymbolicMatrix(global::net.sf.jni4net.utils.Convertor.ArrayStrongJp2C<global::ASquared.SymbolicMath.Symbol[], global::ASquared.SymbolicMath.Symbol>(@__env, values), global::net.sf.jni4net.utils.Convertor.StrongJp2C<global::ASquared.SymbolicMath.OrientationOption>(@__env, orientation));
            global::net.sf.jni4net.utils.Convertor.InitProxy(@__env, @__obj, @__real);
            }catch (global::System.Exception __ex){@__env.ThrowExisting(__ex);}
        }
        
        private static void @__ctorSymbolicMatrix6(global::System.IntPtr @__envp, global::net.sf.jni4net.utils.JniLocalHandle @__class, global::net.sf.jni4net.utils.JniLocalHandle @__obj, global::net.sf.jni4net.utils.JniLocalHandle table) {
            // (Lsystem/Object;)V
            // (LSystem/Data/DataTable;)V
            global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.Wrap(@__envp);
            try {
            global::ASquared.SymbolicMath.SymbolicMatrix @__real = new global::ASquared.SymbolicMath.SymbolicMatrix(global::net.sf.jni4net.utils.Convertor.StrongJp2C<global::System.Data.DataTable>(@__env, table));
            global::net.sf.jni4net.utils.Convertor.InitProxy(@__env, @__obj, @__real);
            }catch (global::System.Exception __ex){@__env.ThrowExisting(__ex);}
        }
        
        new internal sealed class ContructionHelper : global::net.sf.jni4net.utils.IConstructionHelper {
            
            public global::net.sf.jni4net.jni.IJvmProxy CreateProxy(global::net.sf.jni4net.jni.JNIEnv @__env) {
                return new global::ASquared.SymbolicMath.@__SymbolicMatrix(@__env);
            }
        }
    }
    #endregion
}
