//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by jni4net. See http://jni4net.sourceforge.net/ 
//     Runtime Version:4.0.30319.296
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASquared.SymbolicMath {
    
    
    #region Component Designer generated code 
    public partial class Symbol_ {
        
        public static global::java.lang.Class _class {
            get {
                return global::ASquared.SymbolicMath.@__Symbol.staticClass;
            }
        }
    }
    #endregion
    
    #region Component Designer generated code 
    [global::net.sf.jni4net.attributes.JavaProxyAttribute(typeof(global::ASquared.SymbolicMath.Symbol), typeof(global::ASquared.SymbolicMath.Symbol_))]
    [global::net.sf.jni4net.attributes.ClrWrapperAttribute(typeof(global::ASquared.SymbolicMath.Symbol), typeof(global::ASquared.SymbolicMath.Symbol_))]
    internal sealed partial class @__Symbol : global::java.lang.Object {
        
        internal new static global::java.lang.Class staticClass;
        
        private @__Symbol(global::net.sf.jni4net.jni.JNIEnv @__env) : 
                base(@__env) {
        }
        
        private static void InitJNI(global::net.sf.jni4net.jni.JNIEnv @__env, java.lang.Class @__class) {
            global::ASquared.SymbolicMath.@__Symbol.staticClass = @__class;
        }
        
        private static global::System.Collections.Generic.List<global::net.sf.jni4net.jni.JNINativeMethod> @__Init(global::net.sf.jni4net.jni.JNIEnv @__env, global::java.lang.Class @__class) {
            global::System.Type @__type = typeof(__Symbol);
            global::System.Collections.Generic.List<global::net.sf.jni4net.jni.JNINativeMethod> methods = new global::System.Collections.Generic.List<global::net.sf.jni4net.jni.JNINativeMethod>();
            methods.Add(global::net.sf.jni4net.jni.JNINativeMethod.Create(@__type, "getSymbolType", "SymbolType0", "()Lasquared/symbolicmath/SymbolType;"));
            methods.Add(global::net.sf.jni4net.jni.JNINativeMethod.Create(@__type, "Eval", "Eval1", "()D"));
            methods.Add(global::net.sf.jni4net.jni.JNINativeMethod.Create(@__type, "Eval", "Eval2", "(D)D"));
            methods.Add(global::net.sf.jni4net.jni.JNINativeMethod.Create(@__type, "Eval", "Eval3", "([Ljava/lang/String;[D)D"));
            methods.Add(global::net.sf.jni4net.jni.JNINativeMethod.Create(@__type, "Eval", "Eval4", "([D)[D"));
            methods.Add(global::net.sf.jni4net.jni.JNINativeMethod.Create(@__type, "Eval", "Eval5", "([Ljava/lang/String;[[D)[D"));
            methods.Add(global::net.sf.jni4net.jni.JNINativeMethod.Create(@__type, "Eval", "Eval6", "([Lasquared/symbolicmath/Symbol;[Ljava/lang/String;[[D)[D"));
            methods.Add(global::net.sf.jni4net.jni.JNINativeMethod.Create(@__type, "Eval", "Eval7", "([Lasquared/symbolicmath/Symbol;[Ljava/lang/String;[D)[D"));
            methods.Add(global::net.sf.jni4net.jni.JNINativeMethod.Create(@__type, "Subs", "Subs8", "([Ljava/lang/String;[Lsystem/Object;)Lasquared/symbolicmath/Symbol;"));
            methods.Add(global::net.sf.jni4net.jni.JNINativeMethod.Create(@__type, "Subs", "Subs9", "([Ljava/lang/String;[D)Lasquared/symbolicmath/Symbol;"));
            methods.Add(global::net.sf.jni4net.jni.JNINativeMethod.Create(@__type, "Subs", "Subs10", "([Ljava/lang/String;Lasquared/symbolicmath/Symbol;)Lasquared/symbolicmath/Symbol;" +
                        ""));
            methods.Add(global::net.sf.jni4net.jni.JNINativeMethod.Create(@__type, "Subs", "Subs11", "(Ljava/lang/String;D)Lasquared/symbolicmath/Symbol;"));
            methods.Add(global::net.sf.jni4net.jni.JNINativeMethod.Create(@__type, "Subs", "Subs12", "(Ljava/lang/String;Ljava/lang/String;)Lasquared/symbolicmath/Symbol;"));
            methods.Add(global::net.sf.jni4net.jni.JNINativeMethod.Create(@__type, "Subs", "Subs13", "(Ljava/lang/String;Lasquared/symbolicmath/Symbol;)Lasquared/symbolicmath/Symbol;"));
            methods.Add(global::net.sf.jni4net.jni.JNINativeMethod.Create(@__type, "Subs", "Subs14", "([Ljava/lang/String;[[Lsystem/Object;)[Lasquared/symbolicmath/Symbol;"));
            methods.Add(global::net.sf.jni4net.jni.JNINativeMethod.Create(@__type, "Subs", "Subs15", "([Ljava/lang/String;[[D)[Lasquared/symbolicmath/Symbol;"));
            methods.Add(global::net.sf.jni4net.jni.JNINativeMethod.Create(@__type, "IsZero", "IsZero16", "()Z"));
            methods.Add(global::net.sf.jni4net.jni.JNINativeMethod.Create(@__type, "Variables", "Variables17", "()Lsystem/Object;"));
            methods.Add(global::net.sf.jni4net.jni.JNINativeMethod.Create(@__type, "ToNumber", "ToNumber18", "()D"));
            methods.Add(global::net.sf.jni4net.jni.JNINativeMethod.Create(@__type, "ContainsOneOrMoreVariables", "ContainsOneOrMoreVariables19", "()Z"));
            methods.Add(global::net.sf.jni4net.jni.JNINativeMethod.Create(@__type, "IsConstant", "IsConstant20", "()Z"));
            methods.Add(global::net.sf.jni4net.jni.JNINativeMethod.Create(@__type, "Parse", "Parse21", "(Ljava/lang/String;)Lasquared/symbolicmath/Symbol;"));
            methods.Add(global::net.sf.jni4net.jni.JNINativeMethod.Create(@__type, "__ctorSymbol0", "__ctorSymbol0", "(Lnet/sf/jni4net/inj/IClrProxy;)V"));
            methods.Add(global::net.sf.jni4net.jni.JNINativeMethod.Create(@__type, "__ctorSymbol1", "__ctorSymbol1", "(Lnet/sf/jni4net/inj/IClrProxy;D)V"));
            methods.Add(global::net.sf.jni4net.jni.JNINativeMethod.Create(@__type, "__ctorSymbol2", "__ctorSymbol2", "(Lnet/sf/jni4net/inj/IClrProxy;C)V"));
            methods.Add(global::net.sf.jni4net.jni.JNINativeMethod.Create(@__type, "__ctorSymbol3", "__ctorSymbol3", "(Lnet/sf/jni4net/inj/IClrProxy;Ljava/lang/String;)V"));
            methods.Add(global::net.sf.jni4net.jni.JNINativeMethod.Create(@__type, "__ctorSymbol4", "__ctorSymbol4", "(Lnet/sf/jni4net/inj/IClrProxy;Lasquared/symbolicmath/Symbol;Lasquared/symbolicma" +
                        "th/SymbolType;)V"));
            methods.Add(global::net.sf.jni4net.jni.JNINativeMethod.Create(@__type, "__ctorSymbol5", "__ctorSymbol5", "(Lnet/sf/jni4net/inj/IClrProxy;Lasquared/symbolicmath/Symbol;Lasquared/symbolicma" +
                        "th/SymbolType;Lasquared/symbolicmath/Symbol;)V"));
            return methods;
        }
        
        private static global::net.sf.jni4net.utils.JniHandle SymbolType0(global::System.IntPtr @__envp, global::net.sf.jni4net.utils.JniLocalHandle @__obj) {
            // ()Lasquared/symbolicmath/SymbolType;
            // ()LASquared/SymbolicMath/SymbolType;
            global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.Wrap(@__envp);
            global::net.sf.jni4net.utils.JniHandle @__return = default(global::net.sf.jni4net.utils.JniHandle);
            try {
            global::ASquared.SymbolicMath.Symbol @__real = global::net.sf.jni4net.utils.Convertor.StrongJp2C<global::ASquared.SymbolicMath.Symbol>(@__env, @__obj);
            @__return = global::net.sf.jni4net.utils.Convertor.StrongC2Jp<global::ASquared.SymbolicMath.SymbolType>(@__env, @__real.SymbolType);
            }catch (global::System.Exception __ex){@__env.ThrowExisting(__ex);}
            return @__return;
        }
        
        private static double Eval1(global::System.IntPtr @__envp, global::net.sf.jni4net.utils.JniLocalHandle @__obj) {
            // ()D
            // ()D
            global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.Wrap(@__envp);
            double @__return = default(double);
            try {
            global::ASquared.SymbolicMath.Symbol @__real = global::net.sf.jni4net.utils.Convertor.StrongJp2C<global::ASquared.SymbolicMath.Symbol>(@__env, @__obj);
            @__return = ((double)(@__real.Eval()));
            }catch (global::System.Exception __ex){@__env.ThrowExisting(__ex);}
            return @__return;
        }
        
        private static double Eval2(global::System.IntPtr @__envp, global::net.sf.jni4net.utils.JniLocalHandle @__obj, double value) {
            // (D)D
            // (D)D
            global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.Wrap(@__envp);
            double @__return = default(double);
            try {
            global::ASquared.SymbolicMath.Symbol @__real = global::net.sf.jni4net.utils.Convertor.StrongJp2C<global::ASquared.SymbolicMath.Symbol>(@__env, @__obj);
            @__return = ((double)(@__real.Eval(value)));
            }catch (global::System.Exception __ex){@__env.ThrowExisting(__ex);}
            return @__return;
        }
        
        private static double Eval3(global::System.IntPtr @__envp, global::net.sf.jni4net.utils.JniLocalHandle @__obj, global::net.sf.jni4net.utils.JniLocalHandle variables, global::net.sf.jni4net.utils.JniLocalHandle values) {
            // ([Ljava/lang/String;[D)D
            // ([LSystem/String;[D)D
            global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.Wrap(@__envp);
            double @__return = default(double);
            try {
            global::ASquared.SymbolicMath.Symbol @__real = global::net.sf.jni4net.utils.Convertor.StrongJp2C<global::ASquared.SymbolicMath.Symbol>(@__env, @__obj);
            @__return = ((double)(@__real.Eval(global::net.sf.jni4net.utils.Convertor.ArrayStrongJ2CString(@__env, variables), global::net.sf.jni4net.utils.Convertor.ArrayPrimJ2Cdouble(@__env, values))));
            }catch (global::System.Exception __ex){@__env.ThrowExisting(__ex);}
            return @__return;
        }
        
        private static global::net.sf.jni4net.utils.JniHandle Eval4(global::System.IntPtr @__envp, global::net.sf.jni4net.utils.JniLocalHandle @__obj, global::net.sf.jni4net.utils.JniLocalHandle values) {
            // ([D)[D
            // ([D)[D
            global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.Wrap(@__envp);
            global::net.sf.jni4net.utils.JniHandle @__return = default(global::net.sf.jni4net.utils.JniHandle);
            try {
            global::ASquared.SymbolicMath.Symbol @__real = global::net.sf.jni4net.utils.Convertor.StrongJp2C<global::ASquared.SymbolicMath.Symbol>(@__env, @__obj);
            @__return = global::net.sf.jni4net.utils.Convertor.ArrayPrimC2J(@__env, @__real.Eval(global::net.sf.jni4net.utils.Convertor.ArrayPrimJ2Cdouble(@__env, values)));
            }catch (global::System.Exception __ex){@__env.ThrowExisting(__ex);}
            return @__return;
        }
        
        private static global::net.sf.jni4net.utils.JniHandle Eval5(global::System.IntPtr @__envp, global::net.sf.jni4net.utils.JniLocalHandle @__obj, global::net.sf.jni4net.utils.JniLocalHandle variables, global::net.sf.jni4net.utils.JniLocalHandle values) {
            // ([Ljava/lang/String;[[D)[D
            // ([LSystem/String;[[D)[D
            global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.Wrap(@__envp);
            global::net.sf.jni4net.utils.JniHandle @__return = default(global::net.sf.jni4net.utils.JniHandle);
            try {
            global::ASquared.SymbolicMath.Symbol @__real = global::net.sf.jni4net.utils.Convertor.StrongJp2C<global::ASquared.SymbolicMath.Symbol>(@__env, @__obj);
            @__return = global::net.sf.jni4net.utils.Convertor.ArrayPrimC2J(@__env, @__real.Eval(global::net.sf.jni4net.utils.Convertor.ArrayStrongJ2CString(@__env, variables), global::net.sf.jni4net.utils.Convertor.ArrayStrongJp2C<double[][], double[]>(@__env, values)));
            }catch (global::System.Exception __ex){@__env.ThrowExisting(__ex);}
            return @__return;
        }
        
        private static global::net.sf.jni4net.utils.JniHandle Eval6(global::System.IntPtr @__envp, global::net.sf.jni4net.utils.JniLocalHandle @__class, global::net.sf.jni4net.utils.JniLocalHandle fxns, global::net.sf.jni4net.utils.JniLocalHandle variables, global::net.sf.jni4net.utils.JniLocalHandle values) {
            // ([Lasquared/symbolicmath/Symbol;[Ljava/lang/String;[[D)[D
            // ([LASquared/SymbolicMath/Symbol;[LSystem/String;[[D)[D
            global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.Wrap(@__envp);
            global::net.sf.jni4net.utils.JniHandle @__return = default(global::net.sf.jni4net.utils.JniHandle);
            try {
            @__return = global::net.sf.jni4net.utils.Convertor.ArrayPrimC2J(@__env, global::ASquared.SymbolicMath.Symbol.Eval(global::net.sf.jni4net.utils.Convertor.ArrayStrongJp2C<global::ASquared.SymbolicMath.Symbol[], global::ASquared.SymbolicMath.Symbol>(@__env, fxns), global::net.sf.jni4net.utils.Convertor.ArrayStrongJ2CString(@__env, variables), global::net.sf.jni4net.utils.Convertor.ArrayStrongJp2C<double[][], double[]>(@__env, values)));
            }catch (global::System.Exception __ex){@__env.ThrowExisting(__ex);}
            return @__return;
        }
        
        private static global::net.sf.jni4net.utils.JniHandle Eval7(global::System.IntPtr @__envp, global::net.sf.jni4net.utils.JniLocalHandle @__class, global::net.sf.jni4net.utils.JniLocalHandle fxns, global::net.sf.jni4net.utils.JniLocalHandle variables, global::net.sf.jni4net.utils.JniLocalHandle values) {
            // ([Lasquared/symbolicmath/Symbol;[Ljava/lang/String;[D)[D
            // ([LASquared/SymbolicMath/Symbol;[LSystem/String;[D)[D
            global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.Wrap(@__envp);
            global::net.sf.jni4net.utils.JniHandle @__return = default(global::net.sf.jni4net.utils.JniHandle);
            try {
            @__return = global::net.sf.jni4net.utils.Convertor.ArrayPrimC2J(@__env, global::ASquared.SymbolicMath.Symbol.Eval(global::net.sf.jni4net.utils.Convertor.ArrayStrongJp2C<global::ASquared.SymbolicMath.Symbol[], global::ASquared.SymbolicMath.Symbol>(@__env, fxns), global::net.sf.jni4net.utils.Convertor.ArrayStrongJ2CString(@__env, variables), global::net.sf.jni4net.utils.Convertor.ArrayPrimJ2Cdouble(@__env, values)));
            }catch (global::System.Exception __ex){@__env.ThrowExisting(__ex);}
            return @__return;
        }
        
        private static global::net.sf.jni4net.utils.JniHandle Subs8(global::System.IntPtr @__envp, global::net.sf.jni4net.utils.JniLocalHandle @__obj, global::net.sf.jni4net.utils.JniLocalHandle variables, global::net.sf.jni4net.utils.JniLocalHandle values) {
            // ([Ljava/lang/String;[Lsystem/Object;)Lasquared/symbolicmath/Symbol;
            // ([LSystem/String;[LSystem/Object;)LASquared/SymbolicMath/Symbol;
            global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.Wrap(@__envp);
            global::net.sf.jni4net.utils.JniHandle @__return = default(global::net.sf.jni4net.utils.JniHandle);
            try {
            global::ASquared.SymbolicMath.Symbol @__real = global::net.sf.jni4net.utils.Convertor.StrongJp2C<global::ASquared.SymbolicMath.Symbol>(@__env, @__obj);
            @__return = global::net.sf.jni4net.utils.Convertor.StrongC2Jp<global::ASquared.SymbolicMath.Symbol>(@__env, @__real.Subs(global::net.sf.jni4net.utils.Convertor.ArrayStrongJ2CString(@__env, variables), global::net.sf.jni4net.utils.Convertor.ArrayFullJ2C<object[], object>(@__env, values)));
            }catch (global::System.Exception __ex){@__env.ThrowExisting(__ex);}
            return @__return;
        }
        
        private static global::net.sf.jni4net.utils.JniHandle Subs9(global::System.IntPtr @__envp, global::net.sf.jni4net.utils.JniLocalHandle @__obj, global::net.sf.jni4net.utils.JniLocalHandle variables, global::net.sf.jni4net.utils.JniLocalHandle values) {
            // ([Ljava/lang/String;[D)Lasquared/symbolicmath/Symbol;
            // ([LSystem/String;[D)LASquared/SymbolicMath/Symbol;
            global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.Wrap(@__envp);
            global::net.sf.jni4net.utils.JniHandle @__return = default(global::net.sf.jni4net.utils.JniHandle);
            try {
            global::ASquared.SymbolicMath.Symbol @__real = global::net.sf.jni4net.utils.Convertor.StrongJp2C<global::ASquared.SymbolicMath.Symbol>(@__env, @__obj);
            @__return = global::net.sf.jni4net.utils.Convertor.StrongC2Jp<global::ASquared.SymbolicMath.Symbol>(@__env, @__real.Subs(global::net.sf.jni4net.utils.Convertor.ArrayStrongJ2CString(@__env, variables), global::net.sf.jni4net.utils.Convertor.ArrayPrimJ2Cdouble(@__env, values)));
            }catch (global::System.Exception __ex){@__env.ThrowExisting(__ex);}
            return @__return;
        }
        
        private static global::net.sf.jni4net.utils.JniHandle Subs10(global::System.IntPtr @__envp, global::net.sf.jni4net.utils.JniLocalHandle @__obj, global::net.sf.jni4net.utils.JniLocalHandle variables, global::net.sf.jni4net.utils.JniLocalHandle s) {
            // ([Ljava/lang/String;Lasquared/symbolicmath/Symbol;)Lasquared/symbolicmath/Symbol;
            // ([LSystem/String;LASquared/SymbolicMath/Symbol;)LASquared/SymbolicMath/Symbol;
            global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.Wrap(@__envp);
            global::net.sf.jni4net.utils.JniHandle @__return = default(global::net.sf.jni4net.utils.JniHandle);
            try {
            global::ASquared.SymbolicMath.Symbol @__real = global::net.sf.jni4net.utils.Convertor.StrongJp2C<global::ASquared.SymbolicMath.Symbol>(@__env, @__obj);
            @__return = global::net.sf.jni4net.utils.Convertor.StrongC2Jp<global::ASquared.SymbolicMath.Symbol>(@__env, @__real.Subs(global::net.sf.jni4net.utils.Convertor.ArrayStrongJ2CString(@__env, variables), global::net.sf.jni4net.utils.Convertor.StrongJp2C<global::ASquared.SymbolicMath.Symbol>(@__env, s)));
            }catch (global::System.Exception __ex){@__env.ThrowExisting(__ex);}
            return @__return;
        }
        
        private static global::net.sf.jni4net.utils.JniHandle Subs11(global::System.IntPtr @__envp, global::net.sf.jni4net.utils.JniLocalHandle @__obj, global::net.sf.jni4net.utils.JniLocalHandle variable, double value) {
            // (Ljava/lang/String;D)Lasquared/symbolicmath/Symbol;
            // (LSystem/String;D)LASquared/SymbolicMath/Symbol;
            global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.Wrap(@__envp);
            global::net.sf.jni4net.utils.JniHandle @__return = default(global::net.sf.jni4net.utils.JniHandle);
            try {
            global::ASquared.SymbolicMath.Symbol @__real = global::net.sf.jni4net.utils.Convertor.StrongJp2C<global::ASquared.SymbolicMath.Symbol>(@__env, @__obj);
            @__return = global::net.sf.jni4net.utils.Convertor.StrongC2Jp<global::ASquared.SymbolicMath.Symbol>(@__env, @__real.Subs(global::net.sf.jni4net.utils.Convertor.StrongJ2CString(@__env, variable), value));
            }catch (global::System.Exception __ex){@__env.ThrowExisting(__ex);}
            return @__return;
        }
        
        private static global::net.sf.jni4net.utils.JniHandle Subs12(global::System.IntPtr @__envp, global::net.sf.jni4net.utils.JniLocalHandle @__obj, global::net.sf.jni4net.utils.JniLocalHandle variable, global::net.sf.jni4net.utils.JniLocalHandle value) {
            // (Ljava/lang/String;Ljava/lang/String;)Lasquared/symbolicmath/Symbol;
            // (LSystem/String;LSystem/String;)LASquared/SymbolicMath/Symbol;
            global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.Wrap(@__envp);
            global::net.sf.jni4net.utils.JniHandle @__return = default(global::net.sf.jni4net.utils.JniHandle);
            try {
            global::ASquared.SymbolicMath.Symbol @__real = global::net.sf.jni4net.utils.Convertor.StrongJp2C<global::ASquared.SymbolicMath.Symbol>(@__env, @__obj);
            @__return = global::net.sf.jni4net.utils.Convertor.StrongC2Jp<global::ASquared.SymbolicMath.Symbol>(@__env, @__real.Subs(global::net.sf.jni4net.utils.Convertor.StrongJ2CString(@__env, variable), global::net.sf.jni4net.utils.Convertor.StrongJ2CString(@__env, value)));
            }catch (global::System.Exception __ex){@__env.ThrowExisting(__ex);}
            return @__return;
        }
        
        private static global::net.sf.jni4net.utils.JniHandle Subs13(global::System.IntPtr @__envp, global::net.sf.jni4net.utils.JniLocalHandle @__obj, global::net.sf.jni4net.utils.JniLocalHandle variable, global::net.sf.jni4net.utils.JniLocalHandle value) {
            // (Ljava/lang/String;Lasquared/symbolicmath/Symbol;)Lasquared/symbolicmath/Symbol;
            // (LSystem/String;LASquared/SymbolicMath/Symbol;)LASquared/SymbolicMath/Symbol;
            global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.Wrap(@__envp);
            global::net.sf.jni4net.utils.JniHandle @__return = default(global::net.sf.jni4net.utils.JniHandle);
            try {
            global::ASquared.SymbolicMath.Symbol @__real = global::net.sf.jni4net.utils.Convertor.StrongJp2C<global::ASquared.SymbolicMath.Symbol>(@__env, @__obj);
            @__return = global::net.sf.jni4net.utils.Convertor.StrongC2Jp<global::ASquared.SymbolicMath.Symbol>(@__env, @__real.Subs(global::net.sf.jni4net.utils.Convertor.StrongJ2CString(@__env, variable), global::net.sf.jni4net.utils.Convertor.StrongJp2C<global::ASquared.SymbolicMath.Symbol>(@__env, value)));
            }catch (global::System.Exception __ex){@__env.ThrowExisting(__ex);}
            return @__return;
        }
        
        private static global::net.sf.jni4net.utils.JniHandle Subs14(global::System.IntPtr @__envp, global::net.sf.jni4net.utils.JniLocalHandle @__obj, global::net.sf.jni4net.utils.JniLocalHandle variables, global::net.sf.jni4net.utils.JniLocalHandle values) {
            // ([Ljava/lang/String;[[Lsystem/Object;)[Lasquared/symbolicmath/Symbol;
            // ([LSystem/String;[[LSystem/Object;)[LASquared/SymbolicMath/Symbol;
            global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.Wrap(@__envp);
            global::net.sf.jni4net.utils.JniHandle @__return = default(global::net.sf.jni4net.utils.JniHandle);
            try {
            global::ASquared.SymbolicMath.Symbol @__real = global::net.sf.jni4net.utils.Convertor.StrongJp2C<global::ASquared.SymbolicMath.Symbol>(@__env, @__obj);
            @__return = global::net.sf.jni4net.utils.Convertor.ArrayStrongC2Jp<global::ASquared.SymbolicMath.Symbol[], global::ASquared.SymbolicMath.Symbol>(@__env, @__real.Subs(global::net.sf.jni4net.utils.Convertor.ArrayStrongJ2CString(@__env, variables), global::net.sf.jni4net.utils.Convertor.ArrayStrongJp2C<object[][], object[]>(@__env, values)));
            }catch (global::System.Exception __ex){@__env.ThrowExisting(__ex);}
            return @__return;
        }
        
        private static global::net.sf.jni4net.utils.JniHandle Subs15(global::System.IntPtr @__envp, global::net.sf.jni4net.utils.JniLocalHandle @__obj, global::net.sf.jni4net.utils.JniLocalHandle variables, global::net.sf.jni4net.utils.JniLocalHandle values) {
            // ([Ljava/lang/String;[[D)[Lasquared/symbolicmath/Symbol;
            // ([LSystem/String;[[D)[LASquared/SymbolicMath/Symbol;
            global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.Wrap(@__envp);
            global::net.sf.jni4net.utils.JniHandle @__return = default(global::net.sf.jni4net.utils.JniHandle);
            try {
            global::ASquared.SymbolicMath.Symbol @__real = global::net.sf.jni4net.utils.Convertor.StrongJp2C<global::ASquared.SymbolicMath.Symbol>(@__env, @__obj);
            @__return = global::net.sf.jni4net.utils.Convertor.ArrayStrongC2Jp<global::ASquared.SymbolicMath.Symbol[], global::ASquared.SymbolicMath.Symbol>(@__env, @__real.Subs(global::net.sf.jni4net.utils.Convertor.ArrayStrongJ2CString(@__env, variables), global::net.sf.jni4net.utils.Convertor.ArrayStrongJp2C<double[][], double[]>(@__env, values)));
            }catch (global::System.Exception __ex){@__env.ThrowExisting(__ex);}
            return @__return;
        }
        
        private static bool IsZero16(global::System.IntPtr @__envp, global::net.sf.jni4net.utils.JniLocalHandle @__obj) {
            // ()Z
            // ()Z
            global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.Wrap(@__envp);
            bool @__return = default(bool);
            try {
            global::ASquared.SymbolicMath.Symbol @__real = global::net.sf.jni4net.utils.Convertor.StrongJp2C<global::ASquared.SymbolicMath.Symbol>(@__env, @__obj);
            @__return = ((bool)(@__real.IsZero()));
            }catch (global::System.Exception __ex){@__env.ThrowExisting(__ex);}
            return @__return;
        }
        
        private static global::net.sf.jni4net.utils.JniHandle Variables17(global::System.IntPtr @__envp, global::net.sf.jni4net.utils.JniLocalHandle @__obj) {
            // ()Lsystem/Object;
            // ()[[LSystem/Collections/Generic/List`1;
            global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.Wrap(@__envp);
            global::net.sf.jni4net.utils.JniHandle @__return = default(global::net.sf.jni4net.utils.JniHandle);
            try {
            global::ASquared.SymbolicMath.Symbol @__real = global::net.sf.jni4net.utils.Convertor.StrongJp2C<global::ASquared.SymbolicMath.Symbol>(@__env, @__obj);
            @__return = global::net.sf.jni4net.utils.Convertor.StrongC2Jp<global::System.Collections.Generic.List<string>>(@__env, @__real.Variables());
            }catch (global::System.Exception __ex){@__env.ThrowExisting(__ex);}
            return @__return;
        }
        
        private static double ToNumber18(global::System.IntPtr @__envp, global::net.sf.jni4net.utils.JniLocalHandle @__obj) {
            // ()D
            // ()D
            global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.Wrap(@__envp);
            double @__return = default(double);
            try {
            global::ASquared.SymbolicMath.Symbol @__real = global::net.sf.jni4net.utils.Convertor.StrongJp2C<global::ASquared.SymbolicMath.Symbol>(@__env, @__obj);
            @__return = ((double)(@__real.ToNumber()));
            }catch (global::System.Exception __ex){@__env.ThrowExisting(__ex);}
            return @__return;
        }
        
        private static bool ContainsOneOrMoreVariables19(global::System.IntPtr @__envp, global::net.sf.jni4net.utils.JniLocalHandle @__obj) {
            // ()Z
            // ()Z
            global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.Wrap(@__envp);
            bool @__return = default(bool);
            try {
            global::ASquared.SymbolicMath.Symbol @__real = global::net.sf.jni4net.utils.Convertor.StrongJp2C<global::ASquared.SymbolicMath.Symbol>(@__env, @__obj);
            @__return = ((bool)(@__real.ContainsOneOrMoreVariables()));
            }catch (global::System.Exception __ex){@__env.ThrowExisting(__ex);}
            return @__return;
        }
        
        private static bool IsConstant20(global::System.IntPtr @__envp, global::net.sf.jni4net.utils.JniLocalHandle @__obj) {
            // ()Z
            // ()Z
            global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.Wrap(@__envp);
            bool @__return = default(bool);
            try {
            global::ASquared.SymbolicMath.Symbol @__real = global::net.sf.jni4net.utils.Convertor.StrongJp2C<global::ASquared.SymbolicMath.Symbol>(@__env, @__obj);
            @__return = ((bool)(@__real.IsConstant()));
            }catch (global::System.Exception __ex){@__env.ThrowExisting(__ex);}
            return @__return;
        }
        
        private static global::net.sf.jni4net.utils.JniHandle Parse21(global::System.IntPtr @__envp, global::net.sf.jni4net.utils.JniLocalHandle @__class, global::net.sf.jni4net.utils.JniLocalHandle expression) {
            // (Ljava/lang/String;)Lasquared/symbolicmath/Symbol;
            // (LSystem/String;)LASquared/SymbolicMath/Symbol;
            global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.Wrap(@__envp);
            global::net.sf.jni4net.utils.JniHandle @__return = default(global::net.sf.jni4net.utils.JniHandle);
            try {
            @__return = global::net.sf.jni4net.utils.Convertor.StrongC2Jp<global::ASquared.SymbolicMath.Symbol>(@__env, global::ASquared.SymbolicMath.Symbol.Parse(global::net.sf.jni4net.utils.Convertor.StrongJ2CString(@__env, expression)));
            }catch (global::System.Exception __ex){@__env.ThrowExisting(__ex);}
            return @__return;
        }
        
        private static void @__ctorSymbol0(global::System.IntPtr @__envp, global::net.sf.jni4net.utils.JniLocalHandle @__class, global::net.sf.jni4net.utils.JniLocalHandle @__obj) {
            // ()V
            // ()V
            global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.Wrap(@__envp);
            try {
            global::ASquared.SymbolicMath.Symbol @__real = new global::ASquared.SymbolicMath.Symbol();
            global::net.sf.jni4net.utils.Convertor.InitProxy(@__env, @__obj, @__real);
            }catch (global::System.Exception __ex){@__env.ThrowExisting(__ex);}
        }
        
        private static void @__ctorSymbol1(global::System.IntPtr @__envp, global::net.sf.jni4net.utils.JniLocalHandle @__class, global::net.sf.jni4net.utils.JniLocalHandle @__obj, double val) {
            // (D)V
            // (D)V
            global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.Wrap(@__envp);
            try {
            global::ASquared.SymbolicMath.Symbol @__real = new global::ASquared.SymbolicMath.Symbol(val);
            global::net.sf.jni4net.utils.Convertor.InitProxy(@__env, @__obj, @__real);
            }catch (global::System.Exception __ex){@__env.ThrowExisting(__ex);}
        }
        
        private static void @__ctorSymbol2(global::System.IntPtr @__envp, global::net.sf.jni4net.utils.JniLocalHandle @__class, global::net.sf.jni4net.utils.JniLocalHandle @__obj, char val) {
            // (C)V
            // (C)V
            global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.Wrap(@__envp);
            try {
            global::ASquared.SymbolicMath.Symbol @__real = new global::ASquared.SymbolicMath.Symbol(val);
            global::net.sf.jni4net.utils.Convertor.InitProxy(@__env, @__obj, @__real);
            }catch (global::System.Exception __ex){@__env.ThrowExisting(__ex);}
        }
        
        private static void @__ctorSymbol3(global::System.IntPtr @__envp, global::net.sf.jni4net.utils.JniLocalHandle @__class, global::net.sf.jni4net.utils.JniLocalHandle @__obj, global::net.sf.jni4net.utils.JniLocalHandle val) {
            // (Ljava/lang/String;)V
            // (LSystem/String;)V
            global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.Wrap(@__envp);
            try {
            global::ASquared.SymbolicMath.Symbol @__real = new global::ASquared.SymbolicMath.Symbol(global::net.sf.jni4net.utils.Convertor.StrongJ2CString(@__env, val));
            global::net.sf.jni4net.utils.Convertor.InitProxy(@__env, @__obj, @__real);
            }catch (global::System.Exception __ex){@__env.ThrowExisting(__ex);}
        }
        
        private static void @__ctorSymbol4(global::System.IntPtr @__envp, global::net.sf.jni4net.utils.JniLocalHandle @__class, global::net.sf.jni4net.utils.JniLocalHandle @__obj, global::net.sf.jni4net.utils.JniLocalHandle val, global::net.sf.jni4net.utils.JniLocalHandle type) {
            // (Lasquared/symbolicmath/Symbol;Lasquared/symbolicmath/SymbolType;)V
            // (LASquared/SymbolicMath/Symbol;LASquared/SymbolicMath/SymbolType;)V
            global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.Wrap(@__envp);
            try {
            global::ASquared.SymbolicMath.Symbol @__real = new global::ASquared.SymbolicMath.Symbol(global::net.sf.jni4net.utils.Convertor.StrongJp2C<global::ASquared.SymbolicMath.Symbol>(@__env, val), global::net.sf.jni4net.utils.Convertor.StrongJp2C<global::ASquared.SymbolicMath.SymbolType>(@__env, type));
            global::net.sf.jni4net.utils.Convertor.InitProxy(@__env, @__obj, @__real);
            }catch (global::System.Exception __ex){@__env.ThrowExisting(__ex);}
        }
        
        private static void @__ctorSymbol5(global::System.IntPtr @__envp, global::net.sf.jni4net.utils.JniLocalHandle @__class, global::net.sf.jni4net.utils.JniLocalHandle @__obj, global::net.sf.jni4net.utils.JniLocalHandle val, global::net.sf.jni4net.utils.JniLocalHandle type, global::net.sf.jni4net.utils.JniLocalHandle rhs) {
            // (Lasquared/symbolicmath/Symbol;Lasquared/symbolicmath/SymbolType;Lasquared/symbolicmath/Symbol;)V
            // (LASquared/SymbolicMath/Symbol;LASquared/SymbolicMath/SymbolType;LASquared/SymbolicMath/Symbol;)V
            global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.Wrap(@__envp);
            try {
            global::ASquared.SymbolicMath.Symbol @__real = new global::ASquared.SymbolicMath.Symbol(global::net.sf.jni4net.utils.Convertor.StrongJp2C<global::ASquared.SymbolicMath.Symbol>(@__env, val), global::net.sf.jni4net.utils.Convertor.StrongJp2C<global::ASquared.SymbolicMath.SymbolType>(@__env, type), global::net.sf.jni4net.utils.Convertor.StrongJp2C<global::ASquared.SymbolicMath.Symbol>(@__env, rhs));
            global::net.sf.jni4net.utils.Convertor.InitProxy(@__env, @__obj, @__real);
            }catch (global::System.Exception __ex){@__env.ThrowExisting(__ex);}
        }
        
        new internal sealed class ContructionHelper : global::net.sf.jni4net.utils.IConstructionHelper {
            
            public global::net.sf.jni4net.jni.IJvmProxy CreateProxy(global::net.sf.jni4net.jni.JNIEnv @__env) {
                return new global::ASquared.SymbolicMath.@__Symbol(@__env);
            }
        }
    }
    #endregion
}
