//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by jni4net. See http://jni4net.sourceforge.net/ 
//     Runtime Version:4.0.30319.296
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASquared {
    
    
    #region Component Designer generated code 
    public partial class Matrix_ {
        
        public static global::java.lang.Class _class {
            get {
                return global::ASquared.@__Matrix.staticClass;
            }
        }
    }
    #endregion
    
    #region Component Designer generated code 
    [global::net.sf.jni4net.attributes.JavaProxyAttribute(typeof(global::ASquared.Matrix), typeof(global::ASquared.Matrix_))]
    [global::net.sf.jni4net.attributes.ClrWrapperAttribute(typeof(global::ASquared.Matrix), typeof(global::ASquared.Matrix_))]
    internal sealed partial class @__Matrix : global::java.lang.Object {
        
        internal new static global::java.lang.Class staticClass;
        
        private @__Matrix(global::net.sf.jni4net.jni.JNIEnv @__env) : 
                base(@__env) {
        }
        
        private static void InitJNI(global::net.sf.jni4net.jni.JNIEnv @__env, java.lang.Class @__class) {
            global::ASquared.@__Matrix.staticClass = @__class;
        }
        
        private static global::System.Collections.Generic.List<global::net.sf.jni4net.jni.JNINativeMethod> @__Init(global::net.sf.jni4net.jni.JNIEnv @__env, global::java.lang.Class @__class) {
            global::System.Type @__type = typeof(__Matrix);
            global::System.Collections.Generic.List<global::net.sf.jni4net.jni.JNINativeMethod> methods = new global::System.Collections.Generic.List<global::net.sf.jni4net.jni.JNINativeMethod>();
            methods.Add(global::net.sf.jni4net.jni.JNINativeMethod.Create(@__type, "getTabularValues", "TabularValues0", "()Lsystem/Object;"));
            methods.Add(global::net.sf.jni4net.jni.JNINativeMethod.Create(@__type, "setTabularValues", "TabularValues1", "(Lsystem/Object;)V"));
            methods.Add(global::net.sf.jni4net.jni.JNINativeMethod.Create(@__type, "getValues", "Values2", "()[D"));
            methods.Add(global::net.sf.jni4net.jni.JNINativeMethod.Create(@__type, "getNumOfRows", "NumOfRows3", "()I"));
            methods.Add(global::net.sf.jni4net.jni.JNINativeMethod.Create(@__type, "getNumOfCols", "NumOfCols4", "()I"));
            methods.Add(global::net.sf.jni4net.jni.JNINativeMethod.Create(@__type, "getLength", "Length5", "()I"));
            methods.Add(global::net.sf.jni4net.jni.JNINativeMethod.Create(@__type, "getItem", "Item6", "(I)D"));
            methods.Add(global::net.sf.jni4net.jni.JNINativeMethod.Create(@__type, "setItem", "Item7", "(ID)V"));
            methods.Add(global::net.sf.jni4net.jni.JNINativeMethod.Create(@__type, "getItem", "Item8", "(II)D"));
            methods.Add(global::net.sf.jni4net.jni.JNINativeMethod.Create(@__type, "setItem", "Item9", "(IID)V"));
            methods.Add(global::net.sf.jni4net.jni.JNINativeMethod.Create(@__type, "Copy", "Copy10", "()Lasquared/Matrix;"));
            methods.Add(global::net.sf.jni4net.jni.JNINativeMethod.Create(@__type, "ToArray", "ToArray11", "()[D"));
            methods.Add(global::net.sf.jni4net.jni.JNINativeMethod.Create(@__type, "To1DArray", "To1DArray12", "()[D"));
            methods.Add(global::net.sf.jni4net.jni.JNINativeMethod.Create(@__type, "ToRow", "ToRow13", "()Lasquared/Matrix;"));
            methods.Add(global::net.sf.jni4net.jni.JNINativeMethod.Create(@__type, "ToColumn", "ToColumn14", "()Lasquared/Matrix;"));
            methods.Add(global::net.sf.jni4net.jni.JNINativeMethod.Create(@__type, "ConvertArray", "ConvertArray15", "([DZ)[D"));
            methods.Add(global::net.sf.jni4net.jni.JNINativeMethod.Create(@__type, "ConvertArrayToDT", "ConvertArrayToDT16", "([DZ)Lsystem/Object;"));
            methods.Add(global::net.sf.jni4net.jni.JNINativeMethod.Create(@__type, "BuildTable", "BuildTable18", "(IID)Lsystem/Object;"));
            methods.Add(global::net.sf.jni4net.jni.JNINativeMethod.Create(@__type, "InsertRowsAt", "InsertRowsAt20", "(Lasquared/Matrix;I)V"));
            methods.Add(global::net.sf.jni4net.jni.JNINativeMethod.Create(@__type, "InsertColsAt", "InsertColsAt21", "(Lasquared/Matrix;I)V"));
            methods.Add(global::net.sf.jni4net.jni.JNINativeMethod.Create(@__type, "AppendRows", "AppendRows22", "(Lasquared/Matrix;)V"));
            methods.Add(global::net.sf.jni4net.jni.JNINativeMethod.Create(@__type, "AppendRows", "AppendRows23", "(I)V"));
            methods.Add(global::net.sf.jni4net.jni.JNINativeMethod.Create(@__type, "AppendCols", "AppendCols24", "(Lasquared/Matrix;)V"));
            methods.Add(global::net.sf.jni4net.jni.JNINativeMethod.Create(@__type, "AppendCols", "AppendCols25", "(I)V"));
            methods.Add(global::net.sf.jni4net.jni.JNINativeMethod.Create(@__type, "RemoveRowAt", "RemoveRowAt26", "(I)Lasquared/Matrix;"));
            methods.Add(global::net.sf.jni4net.jni.JNINativeMethod.Create(@__type, "RemoveColAt", "RemoveColAt27", "(I)Lasquared/Matrix;"));
            methods.Add(global::net.sf.jni4net.jni.JNINativeMethod.Create(@__type, "MoveRow", "MoveRow28", "(II)V"));
            methods.Add(global::net.sf.jni4net.jni.JNINativeMethod.Create(@__type, "MoveCol", "MoveCol29", "(II)V"));
            methods.Add(global::net.sf.jni4net.jni.JNINativeMethod.Create(@__type, "ReplaceRow", "ReplaceRow30", "(ILasquared/Matrix;)V"));
            methods.Add(global::net.sf.jni4net.jni.JNINativeMethod.Create(@__type, "ReplaceCol", "ReplaceCol31", "(ILasquared/Matrix;)V"));
            methods.Add(global::net.sf.jni4net.jni.JNINativeMethod.Create(@__type, "GetRow", "GetRow32", "(I)Lasquared/Matrix;"));
            methods.Add(global::net.sf.jni4net.jni.JNINativeMethod.Create(@__type, "GetCol", "GetCol33", "(I)Lasquared/Matrix;"));
            methods.Add(global::net.sf.jni4net.jni.JNINativeMethod.Create(@__type, "GetRows", "GetRows34", "([I)Lasquared/Matrix;"));
            methods.Add(global::net.sf.jni4net.jni.JNINativeMethod.Create(@__type, "GetCols", "GetCols35", "([I)Lasquared/Matrix;"));
            methods.Add(global::net.sf.jni4net.jni.JNINativeMethod.Create(@__type, "GetRows", "GetRows36", "(II)Lasquared/Matrix;"));
            methods.Add(global::net.sf.jni4net.jni.JNINativeMethod.Create(@__type, "GetCols", "GetCols37", "(II)Lasquared/Matrix;"));
            methods.Add(global::net.sf.jni4net.jni.JNINativeMethod.Create(@__type, "GetRowArray", "GetRowArray38", "(I)[D"));
            methods.Add(global::net.sf.jni4net.jni.JNINativeMethod.Create(@__type, "GetColArray", "GetColArray39", "(I)[D"));
            methods.Add(global::net.sf.jni4net.jni.JNINativeMethod.Create(@__type, "Max", "Max40", "()D"));
            methods.Add(global::net.sf.jni4net.jni.JNINativeMethod.Create(@__type, "Max", "Max41", "(Lnet/sf/jni4net/Out;Lnet/sf/jni4net/Out;)D"));
            methods.Add(global::net.sf.jni4net.jni.JNINativeMethod.Create(@__type, "Max", "Max42", "(Lnet/sf/jni4net/Out;Lnet/sf/jni4net/Out;Lnet/sf/jni4net/Out;Lnet/sf/jni4net/Out;" +
                        ")D"));
            methods.Add(global::net.sf.jni4net.jni.JNINativeMethod.Create(@__type, "Min", "Min43", "()D"));
            methods.Add(global::net.sf.jni4net.jni.JNINativeMethod.Create(@__type, "Min", "Min44", "(Lnet/sf/jni4net/Out;Lnet/sf/jni4net/Out;)D"));
            methods.Add(global::net.sf.jni4net.jni.JNINativeMethod.Create(@__type, "Min", "Min45", "(Lnet/sf/jni4net/Out;Lnet/sf/jni4net/Out;Lnet/sf/jni4net/Out;Lnet/sf/jni4net/Out;" +
                        ")D"));
            methods.Add(global::net.sf.jni4net.jni.JNINativeMethod.Create(@__type, "Sum", "Sum46", "()D"));
            methods.Add(global::net.sf.jni4net.jni.JNINativeMethod.Create(@__type, "Mean", "Mean47", "()D"));
            methods.Add(global::net.sf.jni4net.jni.JNINativeMethod.Create(@__type, "SumAbs", "SumAbs48", "()D"));
            methods.Add(global::net.sf.jni4net.jni.JNINativeMethod.Create(@__type, "MeanAbs", "MeanAbs49", "()D"));
            methods.Add(global::net.sf.jni4net.jni.JNINativeMethod.Create(@__type, "IsNan", "IsNan50", "()Z"));
            methods.Add(global::net.sf.jni4net.jni.JNINativeMethod.Create(@__type, "Add", "Add51", "(Lasquared/Matrix;)Lasquared/Matrix;"));
            methods.Add(global::net.sf.jni4net.jni.JNINativeMethod.Create(@__type, "Add", "Add52", "(D)Lasquared/Matrix;"));
            methods.Add(global::net.sf.jni4net.jni.JNINativeMethod.Create(@__type, "Mult", "Mult53", "(D)Lasquared/Matrix;"));
            methods.Add(global::net.sf.jni4net.jni.JNINativeMethod.Create(@__type, "Mult", "Mult54", "(Lasquared/Matrix;Lasquared/TransposeOption;)Lasquared/Matrix;"));
            methods.Add(global::net.sf.jni4net.jni.JNINativeMethod.Create(@__type, "ElementwiseMult", "ElementwiseMult55", "(Lasquared/Matrix;)Lasquared/Matrix;"));
            methods.Add(global::net.sf.jni4net.jni.JNINativeMethod.Create(@__type, "ElementwiseDivide", "ElementwiseDivide56", "(Lasquared/Matrix;)Lasquared/Matrix;"));
            methods.Add(global::net.sf.jni4net.jni.JNINativeMethod.Create(@__type, "Pow", "Pow57", "(I)Lasquared/Matrix;"));
            methods.Add(global::net.sf.jni4net.jni.JNINativeMethod.Create(@__type, "Abs", "Abs58", "()Lasquared/Matrix;"));
            methods.Add(global::net.sf.jni4net.jni.JNINativeMethod.Create(@__type, "Transpose", "Transpose59", "()Lasquared/Matrix;"));
            methods.Add(global::net.sf.jni4net.jni.JNINativeMethod.Create(@__type, "Magnitude", "Magnitude60", "()D"));
            methods.Add(global::net.sf.jni4net.jni.JNINativeMethod.Create(@__type, "Pivot", "Pivot61", "(II)V"));
            methods.Add(global::net.sf.jni4net.jni.JNINativeMethod.Create(@__type, "RREF", "RREF62", "()V"));
            methods.Add(global::net.sf.jni4net.jni.JNINativeMethod.Create(@__type, "Inverse", "Inverse63", "()Lasquared/Matrix;"));
            methods.Add(global::net.sf.jni4net.jni.JNINativeMethod.Create(@__type, "SolveLinearSys", "SolveLinearSys64", "(Lasquared/Matrix;Lasquared/Matrix;)Lasquared/Matrix;"));
            methods.Add(global::net.sf.jni4net.jni.JNINativeMethod.Create(@__type, "FromString", "FromString65", "(Ljava/lang/String;)Lasquared/Matrix;"));
            methods.Add(global::net.sf.jni4net.jni.JNINativeMethod.Create(@__type, "Identity", "Identity66", "(I)Lasquared/Matrix;"));
            methods.Add(global::net.sf.jni4net.jni.JNINativeMethod.Create(@__type, "Random", "Random67", "(II)Lasquared/Matrix;"));
            methods.Add(global::net.sf.jni4net.jni.JNINativeMethod.Create(@__type, "RandomInt", "RandomInt68", "(II)Lasquared/Matrix;"));
            methods.Add(global::net.sf.jni4net.jni.JNINativeMethod.Create(@__type, "RandomInt", "RandomInt69", "(III)Lasquared/Matrix;"));
            methods.Add(global::net.sf.jni4net.jni.JNINativeMethod.Create(@__type, "RandomInt", "RandomInt70", "(IIII)Lasquared/Matrix;"));
            methods.Add(global::net.sf.jni4net.jni.JNINativeMethod.Create(@__type, "__ctorMatrix0", "__ctorMatrix0", "(Lnet/sf/jni4net/inj/IClrProxy;)V"));
            methods.Add(global::net.sf.jni4net.jni.JNINativeMethod.Create(@__type, "__ctorMatrix1", "__ctorMatrix1", "(Lnet/sf/jni4net/inj/IClrProxy;I)V"));
            methods.Add(global::net.sf.jni4net.jni.JNINativeMethod.Create(@__type, "__ctorMatrix2", "__ctorMatrix2", "(Lnet/sf/jni4net/inj/IClrProxy;ID)V"));
            methods.Add(global::net.sf.jni4net.jni.JNINativeMethod.Create(@__type, "__ctorMatrix3", "__ctorMatrix3", "(Lnet/sf/jni4net/inj/IClrProxy;II)V"));
            methods.Add(global::net.sf.jni4net.jni.JNINativeMethod.Create(@__type, "__ctorMatrix4", "__ctorMatrix4", "(Lnet/sf/jni4net/inj/IClrProxy;IID)V"));
            methods.Add(global::net.sf.jni4net.jni.JNINativeMethod.Create(@__type, "__ctorMatrix5", "__ctorMatrix5", "(Lnet/sf/jni4net/inj/IClrProxy;[D)V"));
            methods.Add(global::net.sf.jni4net.jni.JNINativeMethod.Create(@__type, "__ctorMatrix6", "__ctorMatrix6", "(Lnet/sf/jni4net/inj/IClrProxy;[DZ)V"));
            methods.Add(global::net.sf.jni4net.jni.JNINativeMethod.Create(@__type, "__ctorMatrix7", "__ctorMatrix7", "(Lnet/sf/jni4net/inj/IClrProxy;Lsystem/Object;)V"));
            return methods;
        }
        
        private static global::net.sf.jni4net.utils.JniHandle TabularValues0(global::System.IntPtr @__envp, global::net.sf.jni4net.utils.JniLocalHandle @__obj) {
            // ()Lsystem/Object;
            // ()LSystem/Data/DataTable;
            global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.Wrap(@__envp);
            global::net.sf.jni4net.utils.JniHandle @__return = default(global::net.sf.jni4net.utils.JniHandle);
            try {
            global::ASquared.Matrix @__real = global::net.sf.jni4net.utils.Convertor.StrongJp2C<global::ASquared.Matrix>(@__env, @__obj);
            @__return = global::net.sf.jni4net.utils.Convertor.StrongC2Jp<global::System.Data.DataTable>(@__env, @__real.TabularValues);
            }catch (global::System.Exception __ex){@__env.ThrowExisting(__ex);}
            return @__return;
        }
        
        private static void TabularValues1(global::System.IntPtr @__envp, global::net.sf.jni4net.utils.JniLocalHandle @__obj, global::net.sf.jni4net.utils.JniLocalHandle value) {
            // (Lsystem/Object;)V
            // (LSystem/Data/DataTable;)V
            global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.Wrap(@__envp);
            try {
            global::ASquared.Matrix @__real = global::net.sf.jni4net.utils.Convertor.StrongJp2C<global::ASquared.Matrix>(@__env, @__obj);
            @__real.TabularValues = global::net.sf.jni4net.utils.Convertor.StrongJp2C<global::System.Data.DataTable>(@__env, value);
            }catch (global::System.Exception __ex){@__env.ThrowExisting(__ex);}
        }
        
        private static global::net.sf.jni4net.utils.JniHandle Values2(global::System.IntPtr @__envp, global::net.sf.jni4net.utils.JniLocalHandle @__obj) {
            // ()[D
            // ()[D
            global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.Wrap(@__envp);
            global::net.sf.jni4net.utils.JniHandle @__return = default(global::net.sf.jni4net.utils.JniHandle);
            try {
            global::ASquared.Matrix @__real = global::net.sf.jni4net.utils.Convertor.StrongJp2C<global::ASquared.Matrix>(@__env, @__obj);
            @__return = global::net.sf.jni4net.utils.Convertor.ArrayStrongC2Jp<double[,], double>(@__env, @__real.Values);
            }catch (global::System.Exception __ex){@__env.ThrowExisting(__ex);}
            return @__return;
        }
        
        private static int NumOfRows3(global::System.IntPtr @__envp, global::net.sf.jni4net.utils.JniLocalHandle @__obj) {
            // ()I
            // ()I
            global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.Wrap(@__envp);
            int @__return = default(int);
            try {
            global::ASquared.Matrix @__real = global::net.sf.jni4net.utils.Convertor.StrongJp2C<global::ASquared.Matrix>(@__env, @__obj);
            @__return = ((int)(@__real.NumOfRows));
            }catch (global::System.Exception __ex){@__env.ThrowExisting(__ex);}
            return @__return;
        }
        
        private static int NumOfCols4(global::System.IntPtr @__envp, global::net.sf.jni4net.utils.JniLocalHandle @__obj) {
            // ()I
            // ()I
            global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.Wrap(@__envp);
            int @__return = default(int);
            try {
            global::ASquared.Matrix @__real = global::net.sf.jni4net.utils.Convertor.StrongJp2C<global::ASquared.Matrix>(@__env, @__obj);
            @__return = ((int)(@__real.NumOfCols));
            }catch (global::System.Exception __ex){@__env.ThrowExisting(__ex);}
            return @__return;
        }
        
        private static int Length5(global::System.IntPtr @__envp, global::net.sf.jni4net.utils.JniLocalHandle @__obj) {
            // ()I
            // ()I
            global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.Wrap(@__envp);
            int @__return = default(int);
            try {
            global::ASquared.Matrix @__real = global::net.sf.jni4net.utils.Convertor.StrongJp2C<global::ASquared.Matrix>(@__env, @__obj);
            @__return = ((int)(@__real.Length));
            }catch (global::System.Exception __ex){@__env.ThrowExisting(__ex);}
            return @__return;
        }
        
        private static double Item6(global::System.IntPtr @__envp, global::net.sf.jni4net.utils.JniLocalHandle @__obj, int index) {
            // (I)D
            // (I)D
            global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.Wrap(@__envp);
            double @__return = default(double);
            try {
            global::ASquared.Matrix @__real = global::net.sf.jni4net.utils.Convertor.StrongJp2C<global::ASquared.Matrix>(@__env, @__obj);
            @__return = ((double)(@__real[index]));
            }catch (global::System.Exception __ex){@__env.ThrowExisting(__ex);}
            return @__return;
        }
        
        private static void Item7(global::System.IntPtr @__envp, global::net.sf.jni4net.utils.JniLocalHandle @__obj, int index, double value) {
            // (ID)V
            // (ID)V
            global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.Wrap(@__envp);
            try {
            global::ASquared.Matrix @__real = global::net.sf.jni4net.utils.Convertor.StrongJp2C<global::ASquared.Matrix>(@__env, @__obj);
            @__real[index] = value;
            }catch (global::System.Exception __ex){@__env.ThrowExisting(__ex);}
        }
        
        private static double Item8(global::System.IntPtr @__envp, global::net.sf.jni4net.utils.JniLocalHandle @__obj, int row, int col) {
            // (II)D
            // (II)D
            global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.Wrap(@__envp);
            double @__return = default(double);
            try {
            global::ASquared.Matrix @__real = global::net.sf.jni4net.utils.Convertor.StrongJp2C<global::ASquared.Matrix>(@__env, @__obj);
            @__return = ((double)(@__real[row, col]));
            }catch (global::System.Exception __ex){@__env.ThrowExisting(__ex);}
            return @__return;
        }
        
        private static void Item9(global::System.IntPtr @__envp, global::net.sf.jni4net.utils.JniLocalHandle @__obj, int row, int col, double value) {
            // (IID)V
            // (IID)V
            global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.Wrap(@__envp);
            try {
            global::ASquared.Matrix @__real = global::net.sf.jni4net.utils.Convertor.StrongJp2C<global::ASquared.Matrix>(@__env, @__obj);
            @__real[row, col] = value;
            }catch (global::System.Exception __ex){@__env.ThrowExisting(__ex);}
        }
        
        private static global::net.sf.jni4net.utils.JniHandle Copy10(global::System.IntPtr @__envp, global::net.sf.jni4net.utils.JniLocalHandle @__obj) {
            // ()Lasquared/Matrix;
            // ()LASquared/Matrix;
            global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.Wrap(@__envp);
            global::net.sf.jni4net.utils.JniHandle @__return = default(global::net.sf.jni4net.utils.JniHandle);
            try {
            global::ASquared.Matrix @__real = global::net.sf.jni4net.utils.Convertor.StrongJp2C<global::ASquared.Matrix>(@__env, @__obj);
            @__return = global::net.sf.jni4net.utils.Convertor.StrongC2Jp<global::ASquared.Matrix>(@__env, @__real.Copy());
            }catch (global::System.Exception __ex){@__env.ThrowExisting(__ex);}
            return @__return;
        }
        
        private static global::net.sf.jni4net.utils.JniHandle ToArray11(global::System.IntPtr @__envp, global::net.sf.jni4net.utils.JniLocalHandle @__obj) {
            // ()[D
            // ()[D
            global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.Wrap(@__envp);
            global::net.sf.jni4net.utils.JniHandle @__return = default(global::net.sf.jni4net.utils.JniHandle);
            try {
            global::ASquared.Matrix @__real = global::net.sf.jni4net.utils.Convertor.StrongJp2C<global::ASquared.Matrix>(@__env, @__obj);
            @__return = global::net.sf.jni4net.utils.Convertor.ArrayStrongC2Jp<double[,], double>(@__env, @__real.ToArray());
            }catch (global::System.Exception __ex){@__env.ThrowExisting(__ex);}
            return @__return;
        }
        
        private static global::net.sf.jni4net.utils.JniHandle To1DArray12(global::System.IntPtr @__envp, global::net.sf.jni4net.utils.JniLocalHandle @__obj) {
            // ()[D
            // ()[D
            global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.Wrap(@__envp);
            global::net.sf.jni4net.utils.JniHandle @__return = default(global::net.sf.jni4net.utils.JniHandle);
            try {
            global::ASquared.Matrix @__real = global::net.sf.jni4net.utils.Convertor.StrongJp2C<global::ASquared.Matrix>(@__env, @__obj);
            @__return = global::net.sf.jni4net.utils.Convertor.ArrayPrimC2J(@__env, @__real.To1DArray());
            }catch (global::System.Exception __ex){@__env.ThrowExisting(__ex);}
            return @__return;
        }
        
        private static global::net.sf.jni4net.utils.JniHandle ToRow13(global::System.IntPtr @__envp, global::net.sf.jni4net.utils.JniLocalHandle @__obj) {
            // ()Lasquared/Matrix;
            // ()LASquared/Matrix;
            global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.Wrap(@__envp);
            global::net.sf.jni4net.utils.JniHandle @__return = default(global::net.sf.jni4net.utils.JniHandle);
            try {
            global::ASquared.Matrix @__real = global::net.sf.jni4net.utils.Convertor.StrongJp2C<global::ASquared.Matrix>(@__env, @__obj);
            @__return = global::net.sf.jni4net.utils.Convertor.StrongC2Jp<global::ASquared.Matrix>(@__env, @__real.ToRow());
            }catch (global::System.Exception __ex){@__env.ThrowExisting(__ex);}
            return @__return;
        }
        
        private static global::net.sf.jni4net.utils.JniHandle ToColumn14(global::System.IntPtr @__envp, global::net.sf.jni4net.utils.JniLocalHandle @__obj) {
            // ()Lasquared/Matrix;
            // ()LASquared/Matrix;
            global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.Wrap(@__envp);
            global::net.sf.jni4net.utils.JniHandle @__return = default(global::net.sf.jni4net.utils.JniHandle);
            try {
            global::ASquared.Matrix @__real = global::net.sf.jni4net.utils.Convertor.StrongJp2C<global::ASquared.Matrix>(@__env, @__obj);
            @__return = global::net.sf.jni4net.utils.Convertor.StrongC2Jp<global::ASquared.Matrix>(@__env, @__real.ToColumn());
            }catch (global::System.Exception __ex){@__env.ThrowExisting(__ex);}
            return @__return;
        }
        
        private static global::net.sf.jni4net.utils.JniHandle ConvertArray15(global::System.IntPtr @__envp, global::net.sf.jni4net.utils.JniLocalHandle @__class, global::net.sf.jni4net.utils.JniLocalHandle vals, bool makesUpRow) {
            // ([DZ)[D
            // ([DZ)[D
            global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.Wrap(@__envp);
            global::net.sf.jni4net.utils.JniHandle @__return = default(global::net.sf.jni4net.utils.JniHandle);
            try {
            @__return = global::net.sf.jni4net.utils.Convertor.StrongC2Jp<double[,]>(@__env, global::ASquared.Matrix.ConvertArray(global::net.sf.jni4net.utils.Convertor.ArrayPrimJ2Cdouble(@__env, vals), makesUpRow));
            }catch (global::System.Exception __ex){@__env.ThrowExisting(__ex);}
            return @__return;
        }
        
        private static global::net.sf.jni4net.utils.JniHandle ConvertArrayToDT16(global::System.IntPtr @__envp, global::net.sf.jni4net.utils.JniLocalHandle @__class, global::net.sf.jni4net.utils.JniLocalHandle vals, bool makesUpRow) {
            // ([DZ)Lsystem/Object;
            // ([DZ)LSystem/Data/DataTable;
            global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.Wrap(@__envp);
            global::net.sf.jni4net.utils.JniHandle @__return = default(global::net.sf.jni4net.utils.JniHandle);
            try {
            @__return = global::net.sf.jni4net.utils.Convertor.StrongC2Jp<global::System.Data.DataTable>(@__env, global::ASquared.Matrix.ConvertArrayToDT(global::net.sf.jni4net.utils.Convertor.ArrayPrimJ2Cdouble(@__env, vals), makesUpRow));
            }catch (global::System.Exception __ex){@__env.ThrowExisting(__ex);}
            return @__return;
        }
        
        private static global::net.sf.jni4net.utils.JniHandle BuildTable18(global::System.IntPtr @__envp, global::net.sf.jni4net.utils.JniLocalHandle @__class, int nrows, int ncols, double defaultVal) {
            // (IID)Lsystem/Object;
            // (IID)LSystem/Data/DataTable;
            global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.Wrap(@__envp);
            global::net.sf.jni4net.utils.JniHandle @__return = default(global::net.sf.jni4net.utils.JniHandle);
            try {
            @__return = global::net.sf.jni4net.utils.Convertor.StrongC2Jp<global::System.Data.DataTable>(@__env, global::ASquared.Matrix.BuildTable(nrows, ncols, defaultVal));
            }catch (global::System.Exception __ex){@__env.ThrowExisting(__ex);}
            return @__return;
        }
        
        private static void InsertRowsAt20(global::System.IntPtr @__envp, global::net.sf.jni4net.utils.JniLocalHandle @__obj, global::net.sf.jni4net.utils.JniLocalHandle vals, int pos) {
            // (Lasquared/Matrix;I)V
            // (LASquared/Matrix;I)V
            global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.Wrap(@__envp);
            try {
            global::ASquared.Matrix @__real = global::net.sf.jni4net.utils.Convertor.StrongJp2C<global::ASquared.Matrix>(@__env, @__obj);
            @__real.InsertRowsAt(global::net.sf.jni4net.utils.Convertor.StrongJp2C<global::ASquared.Matrix>(@__env, vals), pos);
            }catch (global::System.Exception __ex){@__env.ThrowExisting(__ex);}
        }
        
        private static void InsertColsAt21(global::System.IntPtr @__envp, global::net.sf.jni4net.utils.JniLocalHandle @__obj, global::net.sf.jni4net.utils.JniLocalHandle vals, int pos) {
            // (Lasquared/Matrix;I)V
            // (LASquared/Matrix;I)V
            global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.Wrap(@__envp);
            try {
            global::ASquared.Matrix @__real = global::net.sf.jni4net.utils.Convertor.StrongJp2C<global::ASquared.Matrix>(@__env, @__obj);
            @__real.InsertColsAt(global::net.sf.jni4net.utils.Convertor.StrongJp2C<global::ASquared.Matrix>(@__env, vals), pos);
            }catch (global::System.Exception __ex){@__env.ThrowExisting(__ex);}
        }
        
        private static void AppendRows22(global::System.IntPtr @__envp, global::net.sf.jni4net.utils.JniLocalHandle @__obj, global::net.sf.jni4net.utils.JniLocalHandle vals) {
            // (Lasquared/Matrix;)V
            // (LASquared/Matrix;)V
            global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.Wrap(@__envp);
            try {
            global::ASquared.Matrix @__real = global::net.sf.jni4net.utils.Convertor.StrongJp2C<global::ASquared.Matrix>(@__env, @__obj);
            @__real.AppendRows(global::net.sf.jni4net.utils.Convertor.StrongJp2C<global::ASquared.Matrix>(@__env, vals));
            }catch (global::System.Exception __ex){@__env.ThrowExisting(__ex);}
        }
        
        private static void AppendRows23(global::System.IntPtr @__envp, global::net.sf.jni4net.utils.JniLocalHandle @__obj, int nrows) {
            // (I)V
            // (I)V
            global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.Wrap(@__envp);
            try {
            global::ASquared.Matrix @__real = global::net.sf.jni4net.utils.Convertor.StrongJp2C<global::ASquared.Matrix>(@__env, @__obj);
            @__real.AppendRows(nrows);
            }catch (global::System.Exception __ex){@__env.ThrowExisting(__ex);}
        }
        
        private static void AppendCols24(global::System.IntPtr @__envp, global::net.sf.jni4net.utils.JniLocalHandle @__obj, global::net.sf.jni4net.utils.JniLocalHandle vals) {
            // (Lasquared/Matrix;)V
            // (LASquared/Matrix;)V
            global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.Wrap(@__envp);
            try {
            global::ASquared.Matrix @__real = global::net.sf.jni4net.utils.Convertor.StrongJp2C<global::ASquared.Matrix>(@__env, @__obj);
            @__real.AppendCols(global::net.sf.jni4net.utils.Convertor.StrongJp2C<global::ASquared.Matrix>(@__env, vals));
            }catch (global::System.Exception __ex){@__env.ThrowExisting(__ex);}
        }
        
        private static void AppendCols25(global::System.IntPtr @__envp, global::net.sf.jni4net.utils.JniLocalHandle @__obj, int ncols) {
            // (I)V
            // (I)V
            global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.Wrap(@__envp);
            try {
            global::ASquared.Matrix @__real = global::net.sf.jni4net.utils.Convertor.StrongJp2C<global::ASquared.Matrix>(@__env, @__obj);
            @__real.AppendCols(ncols);
            }catch (global::System.Exception __ex){@__env.ThrowExisting(__ex);}
        }
        
        private static global::net.sf.jni4net.utils.JniHandle RemoveRowAt26(global::System.IntPtr @__envp, global::net.sf.jni4net.utils.JniLocalHandle @__obj, int pos) {
            // (I)Lasquared/Matrix;
            // (I)LASquared/Matrix;
            global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.Wrap(@__envp);
            global::net.sf.jni4net.utils.JniHandle @__return = default(global::net.sf.jni4net.utils.JniHandle);
            try {
            global::ASquared.Matrix @__real = global::net.sf.jni4net.utils.Convertor.StrongJp2C<global::ASquared.Matrix>(@__env, @__obj);
            @__return = global::net.sf.jni4net.utils.Convertor.StrongC2Jp<global::ASquared.Matrix>(@__env, @__real.RemoveRowAt(pos));
            }catch (global::System.Exception __ex){@__env.ThrowExisting(__ex);}
            return @__return;
        }
        
        private static global::net.sf.jni4net.utils.JniHandle RemoveColAt27(global::System.IntPtr @__envp, global::net.sf.jni4net.utils.JniLocalHandle @__obj, int pos) {
            // (I)Lasquared/Matrix;
            // (I)LASquared/Matrix;
            global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.Wrap(@__envp);
            global::net.sf.jni4net.utils.JniHandle @__return = default(global::net.sf.jni4net.utils.JniHandle);
            try {
            global::ASquared.Matrix @__real = global::net.sf.jni4net.utils.Convertor.StrongJp2C<global::ASquared.Matrix>(@__env, @__obj);
            @__return = global::net.sf.jni4net.utils.Convertor.StrongC2Jp<global::ASquared.Matrix>(@__env, @__real.RemoveColAt(pos));
            }catch (global::System.Exception __ex){@__env.ThrowExisting(__ex);}
            return @__return;
        }
        
        private static void MoveRow28(global::System.IntPtr @__envp, global::net.sf.jni4net.utils.JniLocalHandle @__obj, int fromPos, int toPos) {
            // (II)V
            // (II)V
            global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.Wrap(@__envp);
            try {
            global::ASquared.Matrix @__real = global::net.sf.jni4net.utils.Convertor.StrongJp2C<global::ASquared.Matrix>(@__env, @__obj);
            @__real.MoveRow(fromPos, toPos);
            }catch (global::System.Exception __ex){@__env.ThrowExisting(__ex);}
        }
        
        private static void MoveCol29(global::System.IntPtr @__envp, global::net.sf.jni4net.utils.JniLocalHandle @__obj, int fromPos, int toPos) {
            // (II)V
            // (II)V
            global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.Wrap(@__envp);
            try {
            global::ASquared.Matrix @__real = global::net.sf.jni4net.utils.Convertor.StrongJp2C<global::ASquared.Matrix>(@__env, @__obj);
            @__real.MoveCol(fromPos, toPos);
            }catch (global::System.Exception __ex){@__env.ThrowExisting(__ex);}
        }
        
        private static void ReplaceRow30(global::System.IntPtr @__envp, global::net.sf.jni4net.utils.JniLocalHandle @__obj, int pos, global::net.sf.jni4net.utils.JniLocalHandle vals) {
            // (ILasquared/Matrix;)V
            // (ILASquared/Matrix;)V
            global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.Wrap(@__envp);
            try {
            global::ASquared.Matrix @__real = global::net.sf.jni4net.utils.Convertor.StrongJp2C<global::ASquared.Matrix>(@__env, @__obj);
            @__real.ReplaceRow(pos, global::net.sf.jni4net.utils.Convertor.StrongJp2C<global::ASquared.Matrix>(@__env, vals));
            }catch (global::System.Exception __ex){@__env.ThrowExisting(__ex);}
        }
        
        private static void ReplaceCol31(global::System.IntPtr @__envp, global::net.sf.jni4net.utils.JniLocalHandle @__obj, int pos, global::net.sf.jni4net.utils.JniLocalHandle vals) {
            // (ILasquared/Matrix;)V
            // (ILASquared/Matrix;)V
            global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.Wrap(@__envp);
            try {
            global::ASquared.Matrix @__real = global::net.sf.jni4net.utils.Convertor.StrongJp2C<global::ASquared.Matrix>(@__env, @__obj);
            @__real.ReplaceCol(pos, global::net.sf.jni4net.utils.Convertor.StrongJp2C<global::ASquared.Matrix>(@__env, vals));
            }catch (global::System.Exception __ex){@__env.ThrowExisting(__ex);}
        }
        
        private static global::net.sf.jni4net.utils.JniHandle GetRow32(global::System.IntPtr @__envp, global::net.sf.jni4net.utils.JniLocalHandle @__obj, int pos) {
            // (I)Lasquared/Matrix;
            // (I)LASquared/Matrix;
            global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.Wrap(@__envp);
            global::net.sf.jni4net.utils.JniHandle @__return = default(global::net.sf.jni4net.utils.JniHandle);
            try {
            global::ASquared.Matrix @__real = global::net.sf.jni4net.utils.Convertor.StrongJp2C<global::ASquared.Matrix>(@__env, @__obj);
            @__return = global::net.sf.jni4net.utils.Convertor.StrongC2Jp<global::ASquared.Matrix>(@__env, @__real.GetRow(pos));
            }catch (global::System.Exception __ex){@__env.ThrowExisting(__ex);}
            return @__return;
        }
        
        private static global::net.sf.jni4net.utils.JniHandle GetCol33(global::System.IntPtr @__envp, global::net.sf.jni4net.utils.JniLocalHandle @__obj, int pos) {
            // (I)Lasquared/Matrix;
            // (I)LASquared/Matrix;
            global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.Wrap(@__envp);
            global::net.sf.jni4net.utils.JniHandle @__return = default(global::net.sf.jni4net.utils.JniHandle);
            try {
            global::ASquared.Matrix @__real = global::net.sf.jni4net.utils.Convertor.StrongJp2C<global::ASquared.Matrix>(@__env, @__obj);
            @__return = global::net.sf.jni4net.utils.Convertor.StrongC2Jp<global::ASquared.Matrix>(@__env, @__real.GetCol(pos));
            }catch (global::System.Exception __ex){@__env.ThrowExisting(__ex);}
            return @__return;
        }
        
        private static global::net.sf.jni4net.utils.JniHandle GetRows34(global::System.IntPtr @__envp, global::net.sf.jni4net.utils.JniLocalHandle @__obj, global::net.sf.jni4net.utils.JniLocalHandle pos) {
            // ([I)Lasquared/Matrix;
            // ([I)LASquared/Matrix;
            global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.Wrap(@__envp);
            global::net.sf.jni4net.utils.JniHandle @__return = default(global::net.sf.jni4net.utils.JniHandle);
            try {
            global::ASquared.Matrix @__real = global::net.sf.jni4net.utils.Convertor.StrongJp2C<global::ASquared.Matrix>(@__env, @__obj);
            @__return = global::net.sf.jni4net.utils.Convertor.StrongC2Jp<global::ASquared.Matrix>(@__env, @__real.GetRows(global::net.sf.jni4net.utils.Convertor.ArrayPrimJ2Cint(@__env, pos)));
            }catch (global::System.Exception __ex){@__env.ThrowExisting(__ex);}
            return @__return;
        }
        
        private static global::net.sf.jni4net.utils.JniHandle GetCols35(global::System.IntPtr @__envp, global::net.sf.jni4net.utils.JniLocalHandle @__obj, global::net.sf.jni4net.utils.JniLocalHandle pos) {
            // ([I)Lasquared/Matrix;
            // ([I)LASquared/Matrix;
            global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.Wrap(@__envp);
            global::net.sf.jni4net.utils.JniHandle @__return = default(global::net.sf.jni4net.utils.JniHandle);
            try {
            global::ASquared.Matrix @__real = global::net.sf.jni4net.utils.Convertor.StrongJp2C<global::ASquared.Matrix>(@__env, @__obj);
            @__return = global::net.sf.jni4net.utils.Convertor.StrongC2Jp<global::ASquared.Matrix>(@__env, @__real.GetCols(global::net.sf.jni4net.utils.Convertor.ArrayPrimJ2Cint(@__env, pos)));
            }catch (global::System.Exception __ex){@__env.ThrowExisting(__ex);}
            return @__return;
        }
        
        private static global::net.sf.jni4net.utils.JniHandle GetRows36(global::System.IntPtr @__envp, global::net.sf.jni4net.utils.JniLocalHandle @__obj, int fromPos, int toPos) {
            // (II)Lasquared/Matrix;
            // (II)LASquared/Matrix;
            global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.Wrap(@__envp);
            global::net.sf.jni4net.utils.JniHandle @__return = default(global::net.sf.jni4net.utils.JniHandle);
            try {
            global::ASquared.Matrix @__real = global::net.sf.jni4net.utils.Convertor.StrongJp2C<global::ASquared.Matrix>(@__env, @__obj);
            @__return = global::net.sf.jni4net.utils.Convertor.StrongC2Jp<global::ASquared.Matrix>(@__env, @__real.GetRows(fromPos, toPos));
            }catch (global::System.Exception __ex){@__env.ThrowExisting(__ex);}
            return @__return;
        }
        
        private static global::net.sf.jni4net.utils.JniHandle GetCols37(global::System.IntPtr @__envp, global::net.sf.jni4net.utils.JniLocalHandle @__obj, int fromPos, int toPos) {
            // (II)Lasquared/Matrix;
            // (II)LASquared/Matrix;
            global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.Wrap(@__envp);
            global::net.sf.jni4net.utils.JniHandle @__return = default(global::net.sf.jni4net.utils.JniHandle);
            try {
            global::ASquared.Matrix @__real = global::net.sf.jni4net.utils.Convertor.StrongJp2C<global::ASquared.Matrix>(@__env, @__obj);
            @__return = global::net.sf.jni4net.utils.Convertor.StrongC2Jp<global::ASquared.Matrix>(@__env, @__real.GetCols(fromPos, toPos));
            }catch (global::System.Exception __ex){@__env.ThrowExisting(__ex);}
            return @__return;
        }
        
        private static global::net.sf.jni4net.utils.JniHandle GetRowArray38(global::System.IntPtr @__envp, global::net.sf.jni4net.utils.JniLocalHandle @__obj, int pos) {
            // (I)[D
            // (I)[D
            global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.Wrap(@__envp);
            global::net.sf.jni4net.utils.JniHandle @__return = default(global::net.sf.jni4net.utils.JniHandle);
            try {
            global::ASquared.Matrix @__real = global::net.sf.jni4net.utils.Convertor.StrongJp2C<global::ASquared.Matrix>(@__env, @__obj);
            @__return = global::net.sf.jni4net.utils.Convertor.ArrayPrimC2J(@__env, @__real.GetRowArray(pos));
            }catch (global::System.Exception __ex){@__env.ThrowExisting(__ex);}
            return @__return;
        }
        
        private static global::net.sf.jni4net.utils.JniHandle GetColArray39(global::System.IntPtr @__envp, global::net.sf.jni4net.utils.JniLocalHandle @__obj, int pos) {
            // (I)[D
            // (I)[D
            global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.Wrap(@__envp);
            global::net.sf.jni4net.utils.JniHandle @__return = default(global::net.sf.jni4net.utils.JniHandle);
            try {
            global::ASquared.Matrix @__real = global::net.sf.jni4net.utils.Convertor.StrongJp2C<global::ASquared.Matrix>(@__env, @__obj);
            @__return = global::net.sf.jni4net.utils.Convertor.ArrayPrimC2J(@__env, @__real.GetColArray(pos));
            }catch (global::System.Exception __ex){@__env.ThrowExisting(__ex);}
            return @__return;
        }
        
        private static double Max40(global::System.IntPtr @__envp, global::net.sf.jni4net.utils.JniLocalHandle @__obj) {
            // ()D
            // ()D
            global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.Wrap(@__envp);
            double @__return = default(double);
            try {
            global::ASquared.Matrix @__real = global::net.sf.jni4net.utils.Convertor.StrongJp2C<global::ASquared.Matrix>(@__env, @__obj);
            @__return = ((double)(@__real.Max()));
            }catch (global::System.Exception __ex){@__env.ThrowExisting(__ex);}
            return @__return;
        }
        
        private static double Max41(global::System.IntPtr @__envp, global::net.sf.jni4net.utils.JniLocalHandle @__obj, global::net.sf.jni4net.utils.JniLocalHandle row, global::net.sf.jni4net.utils.JniLocalHandle col) {
            // (Lnet/sf/jni4net/Out;Lnet/sf/jni4net/Out;)D
            // (II)D
            global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.Wrap(@__envp);
            double @__return = default(double);
            try {
            int @__out_row;
            int @__out_col;
            global::ASquared.Matrix @__real = global::net.sf.jni4net.utils.Convertor.StrongJp2C<global::ASquared.Matrix>(@__env, @__obj);
            @__return = ((double)(@__real.Max(out __out_row, out __out_col)));
            net.sf.jni4net.Out.SetValue<int>(@__env, row, @__out_row);
            net.sf.jni4net.Out.SetValue<int>(@__env, col, @__out_col);
            }catch (global::System.Exception __ex){@__env.ThrowExisting(__ex);}
            return @__return;
        }
        
        private static double Max42(global::System.IntPtr @__envp, global::net.sf.jni4net.utils.JniLocalHandle @__obj, global::net.sf.jni4net.utils.JniLocalHandle row, global::net.sf.jni4net.utils.JniLocalHandle col, global::net.sf.jni4net.utils.JniLocalHandle rowI, global::net.sf.jni4net.utils.JniLocalHandle colI) {
            // (Lnet/sf/jni4net/Out;Lnet/sf/jni4net/Out;Lnet/sf/jni4net/Out;Lnet/sf/jni4net/Out;)D
            // (II[I[I)D
            global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.Wrap(@__envp);
            double @__return = default(double);
            try {
            int @__out_row;
            int @__out_col;
            int[] @__out_rowI;
            int[] @__out_colI;
            global::ASquared.Matrix @__real = global::net.sf.jni4net.utils.Convertor.StrongJp2C<global::ASquared.Matrix>(@__env, @__obj);
            @__return = ((double)(@__real.Max(out __out_row, out __out_col, out __out_rowI, out __out_colI)));
            net.sf.jni4net.Out.SetValue<int>(@__env, row, @__out_row);
            net.sf.jni4net.Out.SetValue<int>(@__env, col, @__out_col);
            net.sf.jni4net.Out.SetValue<int[]>(@__env, rowI, @__out_rowI);
            net.sf.jni4net.Out.SetValue<int[]>(@__env, colI, @__out_colI);
            }catch (global::System.Exception __ex){@__env.ThrowExisting(__ex);}
            return @__return;
        }
        
        private static double Min43(global::System.IntPtr @__envp, global::net.sf.jni4net.utils.JniLocalHandle @__obj) {
            // ()D
            // ()D
            global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.Wrap(@__envp);
            double @__return = default(double);
            try {
            global::ASquared.Matrix @__real = global::net.sf.jni4net.utils.Convertor.StrongJp2C<global::ASquared.Matrix>(@__env, @__obj);
            @__return = ((double)(@__real.Min()));
            }catch (global::System.Exception __ex){@__env.ThrowExisting(__ex);}
            return @__return;
        }
        
        private static double Min44(global::System.IntPtr @__envp, global::net.sf.jni4net.utils.JniLocalHandle @__obj, global::net.sf.jni4net.utils.JniLocalHandle row, global::net.sf.jni4net.utils.JniLocalHandle col) {
            // (Lnet/sf/jni4net/Out;Lnet/sf/jni4net/Out;)D
            // (II)D
            global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.Wrap(@__envp);
            double @__return = default(double);
            try {
            int @__out_row;
            int @__out_col;
            global::ASquared.Matrix @__real = global::net.sf.jni4net.utils.Convertor.StrongJp2C<global::ASquared.Matrix>(@__env, @__obj);
            @__return = ((double)(@__real.Min(out __out_row, out __out_col)));
            net.sf.jni4net.Out.SetValue<int>(@__env, row, @__out_row);
            net.sf.jni4net.Out.SetValue<int>(@__env, col, @__out_col);
            }catch (global::System.Exception __ex){@__env.ThrowExisting(__ex);}
            return @__return;
        }
        
        private static double Min45(global::System.IntPtr @__envp, global::net.sf.jni4net.utils.JniLocalHandle @__obj, global::net.sf.jni4net.utils.JniLocalHandle row, global::net.sf.jni4net.utils.JniLocalHandle col, global::net.sf.jni4net.utils.JniLocalHandle rowI, global::net.sf.jni4net.utils.JniLocalHandle colI) {
            // (Lnet/sf/jni4net/Out;Lnet/sf/jni4net/Out;Lnet/sf/jni4net/Out;Lnet/sf/jni4net/Out;)D
            // (II[I[I)D
            global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.Wrap(@__envp);
            double @__return = default(double);
            try {
            int @__out_row;
            int @__out_col;
            int[] @__out_rowI;
            int[] @__out_colI;
            global::ASquared.Matrix @__real = global::net.sf.jni4net.utils.Convertor.StrongJp2C<global::ASquared.Matrix>(@__env, @__obj);
            @__return = ((double)(@__real.Min(out __out_row, out __out_col, out __out_rowI, out __out_colI)));
            net.sf.jni4net.Out.SetValue<int>(@__env, row, @__out_row);
            net.sf.jni4net.Out.SetValue<int>(@__env, col, @__out_col);
            net.sf.jni4net.Out.SetValue<int[]>(@__env, rowI, @__out_rowI);
            net.sf.jni4net.Out.SetValue<int[]>(@__env, colI, @__out_colI);
            }catch (global::System.Exception __ex){@__env.ThrowExisting(__ex);}
            return @__return;
        }
        
        private static double Sum46(global::System.IntPtr @__envp, global::net.sf.jni4net.utils.JniLocalHandle @__obj) {
            // ()D
            // ()D
            global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.Wrap(@__envp);
            double @__return = default(double);
            try {
            global::ASquared.Matrix @__real = global::net.sf.jni4net.utils.Convertor.StrongJp2C<global::ASquared.Matrix>(@__env, @__obj);
            @__return = ((double)(@__real.Sum()));
            }catch (global::System.Exception __ex){@__env.ThrowExisting(__ex);}
            return @__return;
        }
        
        private static double Mean47(global::System.IntPtr @__envp, global::net.sf.jni4net.utils.JniLocalHandle @__obj) {
            // ()D
            // ()D
            global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.Wrap(@__envp);
            double @__return = default(double);
            try {
            global::ASquared.Matrix @__real = global::net.sf.jni4net.utils.Convertor.StrongJp2C<global::ASquared.Matrix>(@__env, @__obj);
            @__return = ((double)(@__real.Mean()));
            }catch (global::System.Exception __ex){@__env.ThrowExisting(__ex);}
            return @__return;
        }
        
        private static double SumAbs48(global::System.IntPtr @__envp, global::net.sf.jni4net.utils.JniLocalHandle @__obj) {
            // ()D
            // ()D
            global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.Wrap(@__envp);
            double @__return = default(double);
            try {
            global::ASquared.Matrix @__real = global::net.sf.jni4net.utils.Convertor.StrongJp2C<global::ASquared.Matrix>(@__env, @__obj);
            @__return = ((double)(@__real.SumAbs()));
            }catch (global::System.Exception __ex){@__env.ThrowExisting(__ex);}
            return @__return;
        }
        
        private static double MeanAbs49(global::System.IntPtr @__envp, global::net.sf.jni4net.utils.JniLocalHandle @__obj) {
            // ()D
            // ()D
            global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.Wrap(@__envp);
            double @__return = default(double);
            try {
            global::ASquared.Matrix @__real = global::net.sf.jni4net.utils.Convertor.StrongJp2C<global::ASquared.Matrix>(@__env, @__obj);
            @__return = ((double)(@__real.MeanAbs()));
            }catch (global::System.Exception __ex){@__env.ThrowExisting(__ex);}
            return @__return;
        }
        
        private static bool IsNan50(global::System.IntPtr @__envp, global::net.sf.jni4net.utils.JniLocalHandle @__obj) {
            // ()Z
            // ()Z
            global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.Wrap(@__envp);
            bool @__return = default(bool);
            try {
            global::ASquared.Matrix @__real = global::net.sf.jni4net.utils.Convertor.StrongJp2C<global::ASquared.Matrix>(@__env, @__obj);
            @__return = ((bool)(@__real.IsNan()));
            }catch (global::System.Exception __ex){@__env.ThrowExisting(__ex);}
            return @__return;
        }
        
        private static global::net.sf.jni4net.utils.JniHandle Add51(global::System.IntPtr @__envp, global::net.sf.jni4net.utils.JniLocalHandle @__obj, global::net.sf.jni4net.utils.JniLocalHandle m) {
            // (Lasquared/Matrix;)Lasquared/Matrix;
            // (LASquared/Matrix;)LASquared/Matrix;
            global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.Wrap(@__envp);
            global::net.sf.jni4net.utils.JniHandle @__return = default(global::net.sf.jni4net.utils.JniHandle);
            try {
            global::ASquared.Matrix @__real = global::net.sf.jni4net.utils.Convertor.StrongJp2C<global::ASquared.Matrix>(@__env, @__obj);
            @__return = global::net.sf.jni4net.utils.Convertor.StrongC2Jp<global::ASquared.Matrix>(@__env, @__real.Add(global::net.sf.jni4net.utils.Convertor.StrongJp2C<global::ASquared.Matrix>(@__env, m)));
            }catch (global::System.Exception __ex){@__env.ThrowExisting(__ex);}
            return @__return;
        }
        
        private static global::net.sf.jni4net.utils.JniHandle Add52(global::System.IntPtr @__envp, global::net.sf.jni4net.utils.JniLocalHandle @__obj, double val) {
            // (D)Lasquared/Matrix;
            // (D)LASquared/Matrix;
            global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.Wrap(@__envp);
            global::net.sf.jni4net.utils.JniHandle @__return = default(global::net.sf.jni4net.utils.JniHandle);
            try {
            global::ASquared.Matrix @__real = global::net.sf.jni4net.utils.Convertor.StrongJp2C<global::ASquared.Matrix>(@__env, @__obj);
            @__return = global::net.sf.jni4net.utils.Convertor.StrongC2Jp<global::ASquared.Matrix>(@__env, @__real.Add(val));
            }catch (global::System.Exception __ex){@__env.ThrowExisting(__ex);}
            return @__return;
        }
        
        private static global::net.sf.jni4net.utils.JniHandle Mult53(global::System.IntPtr @__envp, global::net.sf.jni4net.utils.JniLocalHandle @__obj, double scalar) {
            // (D)Lasquared/Matrix;
            // (D)LASquared/Matrix;
            global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.Wrap(@__envp);
            global::net.sf.jni4net.utils.JniHandle @__return = default(global::net.sf.jni4net.utils.JniHandle);
            try {
            global::ASquared.Matrix @__real = global::net.sf.jni4net.utils.Convertor.StrongJp2C<global::ASquared.Matrix>(@__env, @__obj);
            @__return = global::net.sf.jni4net.utils.Convertor.StrongC2Jp<global::ASquared.Matrix>(@__env, @__real.Mult(scalar));
            }catch (global::System.Exception __ex){@__env.ThrowExisting(__ex);}
            return @__return;
        }
        
        private static global::net.sf.jni4net.utils.JniHandle Mult54(global::System.IntPtr @__envp, global::net.sf.jni4net.utils.JniLocalHandle @__obj, global::net.sf.jni4net.utils.JniLocalHandle m, global::net.sf.jni4net.utils.JniLocalHandle tOpt) {
            // (Lasquared/Matrix;Lasquared/TransposeOption;)Lasquared/Matrix;
            // (LASquared/Matrix;LASquared/TransposeOption;)LASquared/Matrix;
            global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.Wrap(@__envp);
            global::net.sf.jni4net.utils.JniHandle @__return = default(global::net.sf.jni4net.utils.JniHandle);
            try {
            global::ASquared.Matrix @__real = global::net.sf.jni4net.utils.Convertor.StrongJp2C<global::ASquared.Matrix>(@__env, @__obj);
            @__return = global::net.sf.jni4net.utils.Convertor.StrongC2Jp<global::ASquared.Matrix>(@__env, @__real.Mult(global::net.sf.jni4net.utils.Convertor.StrongJp2C<global::ASquared.Matrix>(@__env, m), global::net.sf.jni4net.utils.Convertor.StrongJp2C<global::ASquared.TransposeOption>(@__env, tOpt)));
            }catch (global::System.Exception __ex){@__env.ThrowExisting(__ex);}
            return @__return;
        }
        
        private static global::net.sf.jni4net.utils.JniHandle ElementwiseMult55(global::System.IntPtr @__envp, global::net.sf.jni4net.utils.JniLocalHandle @__obj, global::net.sf.jni4net.utils.JniLocalHandle m) {
            // (Lasquared/Matrix;)Lasquared/Matrix;
            // (LASquared/Matrix;)LASquared/Matrix;
            global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.Wrap(@__envp);
            global::net.sf.jni4net.utils.JniHandle @__return = default(global::net.sf.jni4net.utils.JniHandle);
            try {
            global::ASquared.Matrix @__real = global::net.sf.jni4net.utils.Convertor.StrongJp2C<global::ASquared.Matrix>(@__env, @__obj);
            @__return = global::net.sf.jni4net.utils.Convertor.StrongC2Jp<global::ASquared.Matrix>(@__env, @__real.ElementwiseMult(global::net.sf.jni4net.utils.Convertor.StrongJp2C<global::ASquared.Matrix>(@__env, m)));
            }catch (global::System.Exception __ex){@__env.ThrowExisting(__ex);}
            return @__return;
        }
        
        private static global::net.sf.jni4net.utils.JniHandle ElementwiseDivide56(global::System.IntPtr @__envp, global::net.sf.jni4net.utils.JniLocalHandle @__obj, global::net.sf.jni4net.utils.JniLocalHandle m) {
            // (Lasquared/Matrix;)Lasquared/Matrix;
            // (LASquared/Matrix;)LASquared/Matrix;
            global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.Wrap(@__envp);
            global::net.sf.jni4net.utils.JniHandle @__return = default(global::net.sf.jni4net.utils.JniHandle);
            try {
            global::ASquared.Matrix @__real = global::net.sf.jni4net.utils.Convertor.StrongJp2C<global::ASquared.Matrix>(@__env, @__obj);
            @__return = global::net.sf.jni4net.utils.Convertor.StrongC2Jp<global::ASquared.Matrix>(@__env, @__real.ElementwiseDivide(global::net.sf.jni4net.utils.Convertor.StrongJp2C<global::ASquared.Matrix>(@__env, m)));
            }catch (global::System.Exception __ex){@__env.ThrowExisting(__ex);}
            return @__return;
        }
        
        private static global::net.sf.jni4net.utils.JniHandle Pow57(global::System.IntPtr @__envp, global::net.sf.jni4net.utils.JniLocalHandle @__obj, int b) {
            // (I)Lasquared/Matrix;
            // (I)LASquared/Matrix;
            global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.Wrap(@__envp);
            global::net.sf.jni4net.utils.JniHandle @__return = default(global::net.sf.jni4net.utils.JniHandle);
            try {
            global::ASquared.Matrix @__real = global::net.sf.jni4net.utils.Convertor.StrongJp2C<global::ASquared.Matrix>(@__env, @__obj);
            @__return = global::net.sf.jni4net.utils.Convertor.StrongC2Jp<global::ASquared.Matrix>(@__env, @__real.Pow(b));
            }catch (global::System.Exception __ex){@__env.ThrowExisting(__ex);}
            return @__return;
        }
        
        private static global::net.sf.jni4net.utils.JniHandle Abs58(global::System.IntPtr @__envp, global::net.sf.jni4net.utils.JniLocalHandle @__obj) {
            // ()Lasquared/Matrix;
            // ()LASquared/Matrix;
            global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.Wrap(@__envp);
            global::net.sf.jni4net.utils.JniHandle @__return = default(global::net.sf.jni4net.utils.JniHandle);
            try {
            global::ASquared.Matrix @__real = global::net.sf.jni4net.utils.Convertor.StrongJp2C<global::ASquared.Matrix>(@__env, @__obj);
            @__return = global::net.sf.jni4net.utils.Convertor.StrongC2Jp<global::ASquared.Matrix>(@__env, @__real.Abs());
            }catch (global::System.Exception __ex){@__env.ThrowExisting(__ex);}
            return @__return;
        }
        
        private static global::net.sf.jni4net.utils.JniHandle Transpose59(global::System.IntPtr @__envp, global::net.sf.jni4net.utils.JniLocalHandle @__obj) {
            // ()Lasquared/Matrix;
            // ()LASquared/Matrix;
            global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.Wrap(@__envp);
            global::net.sf.jni4net.utils.JniHandle @__return = default(global::net.sf.jni4net.utils.JniHandle);
            try {
            global::ASquared.Matrix @__real = global::net.sf.jni4net.utils.Convertor.StrongJp2C<global::ASquared.Matrix>(@__env, @__obj);
            @__return = global::net.sf.jni4net.utils.Convertor.StrongC2Jp<global::ASquared.Matrix>(@__env, @__real.Transpose());
            }catch (global::System.Exception __ex){@__env.ThrowExisting(__ex);}
            return @__return;
        }
        
        private static double Magnitude60(global::System.IntPtr @__envp, global::net.sf.jni4net.utils.JniLocalHandle @__obj) {
            // ()D
            // ()D
            global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.Wrap(@__envp);
            double @__return = default(double);
            try {
            global::ASquared.Matrix @__real = global::net.sf.jni4net.utils.Convertor.StrongJp2C<global::ASquared.Matrix>(@__env, @__obj);
            @__return = ((double)(@__real.Magnitude()));
            }catch (global::System.Exception __ex){@__env.ThrowExisting(__ex);}
            return @__return;
        }
        
        private static void Pivot61(global::System.IntPtr @__envp, global::net.sf.jni4net.utils.JniLocalHandle @__obj, int row, int col) {
            // (II)V
            // (II)V
            global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.Wrap(@__envp);
            try {
            global::ASquared.Matrix @__real = global::net.sf.jni4net.utils.Convertor.StrongJp2C<global::ASquared.Matrix>(@__env, @__obj);
            @__real.Pivot(row, col);
            }catch (global::System.Exception __ex){@__env.ThrowExisting(__ex);}
        }
        
        private static void RREF62(global::System.IntPtr @__envp, global::net.sf.jni4net.utils.JniLocalHandle @__obj) {
            // ()V
            // ()V
            global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.Wrap(@__envp);
            try {
            global::ASquared.Matrix @__real = global::net.sf.jni4net.utils.Convertor.StrongJp2C<global::ASquared.Matrix>(@__env, @__obj);
            @__real.RREF();
            }catch (global::System.Exception __ex){@__env.ThrowExisting(__ex);}
        }
        
        private static global::net.sf.jni4net.utils.JniHandle Inverse63(global::System.IntPtr @__envp, global::net.sf.jni4net.utils.JniLocalHandle @__obj) {
            // ()Lasquared/Matrix;
            // ()LASquared/Matrix;
            global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.Wrap(@__envp);
            global::net.sf.jni4net.utils.JniHandle @__return = default(global::net.sf.jni4net.utils.JniHandle);
            try {
            global::ASquared.Matrix @__real = global::net.sf.jni4net.utils.Convertor.StrongJp2C<global::ASquared.Matrix>(@__env, @__obj);
            @__return = global::net.sf.jni4net.utils.Convertor.StrongC2Jp<global::ASquared.Matrix>(@__env, @__real.Inverse());
            }catch (global::System.Exception __ex){@__env.ThrowExisting(__ex);}
            return @__return;
        }
        
        private static global::net.sf.jni4net.utils.JniHandle SolveLinearSys64(global::System.IntPtr @__envp, global::net.sf.jni4net.utils.JniLocalHandle @__class, global::net.sf.jni4net.utils.JniLocalHandle A, global::net.sf.jni4net.utils.JniLocalHandle b) {
            // (Lasquared/Matrix;Lasquared/Matrix;)Lasquared/Matrix;
            // (LASquared/Matrix;LASquared/Matrix;)LASquared/Matrix;
            global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.Wrap(@__envp);
            global::net.sf.jni4net.utils.JniHandle @__return = default(global::net.sf.jni4net.utils.JniHandle);
            try {
            @__return = global::net.sf.jni4net.utils.Convertor.StrongC2Jp<global::ASquared.Matrix>(@__env, global::ASquared.Matrix.SolveLinearSys(global::net.sf.jni4net.utils.Convertor.StrongJp2C<global::ASquared.Matrix>(@__env, A), global::net.sf.jni4net.utils.Convertor.StrongJp2C<global::ASquared.Matrix>(@__env, b)));
            }catch (global::System.Exception __ex){@__env.ThrowExisting(__ex);}
            return @__return;
        }
        
        private static global::net.sf.jni4net.utils.JniHandle FromString65(global::System.IntPtr @__envp, global::net.sf.jni4net.utils.JniLocalHandle @__class, global::net.sf.jni4net.utils.JniLocalHandle matrix) {
            // (Ljava/lang/String;)Lasquared/Matrix;
            // (LSystem/String;)LASquared/Matrix;
            global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.Wrap(@__envp);
            global::net.sf.jni4net.utils.JniHandle @__return = default(global::net.sf.jni4net.utils.JniHandle);
            try {
            @__return = global::net.sf.jni4net.utils.Convertor.StrongC2Jp<global::ASquared.Matrix>(@__env, global::ASquared.Matrix.FromString(global::net.sf.jni4net.utils.Convertor.StrongJ2CString(@__env, matrix)));
            }catch (global::System.Exception __ex){@__env.ThrowExisting(__ex);}
            return @__return;
        }
        
        private static global::net.sf.jni4net.utils.JniHandle Identity66(global::System.IntPtr @__envp, global::net.sf.jni4net.utils.JniLocalHandle @__class, int n) {
            // (I)Lasquared/Matrix;
            // (I)LASquared/Matrix;
            global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.Wrap(@__envp);
            global::net.sf.jni4net.utils.JniHandle @__return = default(global::net.sf.jni4net.utils.JniHandle);
            try {
            @__return = global::net.sf.jni4net.utils.Convertor.StrongC2Jp<global::ASquared.Matrix>(@__env, global::ASquared.Matrix.Identity(n));
            }catch (global::System.Exception __ex){@__env.ThrowExisting(__ex);}
            return @__return;
        }
        
        private static global::net.sf.jni4net.utils.JniHandle Random67(global::System.IntPtr @__envp, global::net.sf.jni4net.utils.JniLocalHandle @__class, int nrows, int ncols) {
            // (II)Lasquared/Matrix;
            // (II)LASquared/Matrix;
            global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.Wrap(@__envp);
            global::net.sf.jni4net.utils.JniHandle @__return = default(global::net.sf.jni4net.utils.JniHandle);
            try {
            @__return = global::net.sf.jni4net.utils.Convertor.StrongC2Jp<global::ASquared.Matrix>(@__env, global::ASquared.Matrix.Random(nrows, ncols));
            }catch (global::System.Exception __ex){@__env.ThrowExisting(__ex);}
            return @__return;
        }
        
        private static global::net.sf.jni4net.utils.JniHandle RandomInt68(global::System.IntPtr @__envp, global::net.sf.jni4net.utils.JniLocalHandle @__class, int nrows, int ncols) {
            // (II)Lasquared/Matrix;
            // (II)LASquared/Matrix;
            global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.Wrap(@__envp);
            global::net.sf.jni4net.utils.JniHandle @__return = default(global::net.sf.jni4net.utils.JniHandle);
            try {
            @__return = global::net.sf.jni4net.utils.Convertor.StrongC2Jp<global::ASquared.Matrix>(@__env, global::ASquared.Matrix.RandomInt(nrows, ncols));
            }catch (global::System.Exception __ex){@__env.ThrowExisting(__ex);}
            return @__return;
        }
        
        private static global::net.sf.jni4net.utils.JniHandle RandomInt69(global::System.IntPtr @__envp, global::net.sf.jni4net.utils.JniLocalHandle @__class, int nrows, int ncols, int maxValue) {
            // (III)Lasquared/Matrix;
            // (III)LASquared/Matrix;
            global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.Wrap(@__envp);
            global::net.sf.jni4net.utils.JniHandle @__return = default(global::net.sf.jni4net.utils.JniHandle);
            try {
            @__return = global::net.sf.jni4net.utils.Convertor.StrongC2Jp<global::ASquared.Matrix>(@__env, global::ASquared.Matrix.RandomInt(nrows, ncols, maxValue));
            }catch (global::System.Exception __ex){@__env.ThrowExisting(__ex);}
            return @__return;
        }
        
        private static global::net.sf.jni4net.utils.JniHandle RandomInt70(global::System.IntPtr @__envp, global::net.sf.jni4net.utils.JniLocalHandle @__class, int nrows, int ncols, int minValue, int maxValue) {
            // (IIII)Lasquared/Matrix;
            // (IIII)LASquared/Matrix;
            global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.Wrap(@__envp);
            global::net.sf.jni4net.utils.JniHandle @__return = default(global::net.sf.jni4net.utils.JniHandle);
            try {
            @__return = global::net.sf.jni4net.utils.Convertor.StrongC2Jp<global::ASquared.Matrix>(@__env, global::ASquared.Matrix.RandomInt(nrows, ncols, minValue, maxValue));
            }catch (global::System.Exception __ex){@__env.ThrowExisting(__ex);}
            return @__return;
        }
        
        private static void @__ctorMatrix0(global::System.IntPtr @__envp, global::net.sf.jni4net.utils.JniLocalHandle @__class, global::net.sf.jni4net.utils.JniLocalHandle @__obj) {
            // ()V
            // ()V
            global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.Wrap(@__envp);
            try {
            global::ASquared.Matrix @__real = new global::ASquared.Matrix();
            global::net.sf.jni4net.utils.Convertor.InitProxy(@__env, @__obj, @__real);
            }catch (global::System.Exception __ex){@__env.ThrowExisting(__ex);}
        }
        
        private static void @__ctorMatrix1(global::System.IntPtr @__envp, global::net.sf.jni4net.utils.JniLocalHandle @__class, global::net.sf.jni4net.utils.JniLocalHandle @__obj, int nrows) {
            // (I)V
            // (I)V
            global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.Wrap(@__envp);
            try {
            global::ASquared.Matrix @__real = new global::ASquared.Matrix(nrows);
            global::net.sf.jni4net.utils.Convertor.InitProxy(@__env, @__obj, @__real);
            }catch (global::System.Exception __ex){@__env.ThrowExisting(__ex);}
        }
        
        private static void @__ctorMatrix2(global::System.IntPtr @__envp, global::net.sf.jni4net.utils.JniLocalHandle @__class, global::net.sf.jni4net.utils.JniLocalHandle @__obj, int nrows, double defaultVal) {
            // (ID)V
            // (ID)V
            global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.Wrap(@__envp);
            try {
            global::ASquared.Matrix @__real = new global::ASquared.Matrix(nrows, defaultVal);
            global::net.sf.jni4net.utils.Convertor.InitProxy(@__env, @__obj, @__real);
            }catch (global::System.Exception __ex){@__env.ThrowExisting(__ex);}
        }
        
        private static void @__ctorMatrix3(global::System.IntPtr @__envp, global::net.sf.jni4net.utils.JniLocalHandle @__class, global::net.sf.jni4net.utils.JniLocalHandle @__obj, int nrows, int ncols) {
            // (II)V
            // (II)V
            global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.Wrap(@__envp);
            try {
            global::ASquared.Matrix @__real = new global::ASquared.Matrix(nrows, ncols);
            global::net.sf.jni4net.utils.Convertor.InitProxy(@__env, @__obj, @__real);
            }catch (global::System.Exception __ex){@__env.ThrowExisting(__ex);}
        }
        
        private static void @__ctorMatrix4(global::System.IntPtr @__envp, global::net.sf.jni4net.utils.JniLocalHandle @__class, global::net.sf.jni4net.utils.JniLocalHandle @__obj, int nrows, int ncols, double defaultVal) {
            // (IID)V
            // (IID)V
            global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.Wrap(@__envp);
            try {
            global::ASquared.Matrix @__real = new global::ASquared.Matrix(nrows, ncols, defaultVal);
            global::net.sf.jni4net.utils.Convertor.InitProxy(@__env, @__obj, @__real);
            }catch (global::System.Exception __ex){@__env.ThrowExisting(__ex);}
        }
        
        private static void @__ctorMatrix5(global::System.IntPtr @__envp, global::net.sf.jni4net.utils.JniLocalHandle @__class, global::net.sf.jni4net.utils.JniLocalHandle @__obj, global::net.sf.jni4net.utils.JniLocalHandle vals) {
            // ([D)V
            // ([D)V
            global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.Wrap(@__envp);
            try {
            global::ASquared.Matrix @__real = new global::ASquared.Matrix(global::net.sf.jni4net.utils.Convertor.ArrayPrimJ2Cdouble(@__env, vals));
            global::net.sf.jni4net.utils.Convertor.InitProxy(@__env, @__obj, @__real);
            }catch (global::System.Exception __ex){@__env.ThrowExisting(__ex);}
        }
        
        private static void @__ctorMatrix6(global::System.IntPtr @__envp, global::net.sf.jni4net.utils.JniLocalHandle @__class, global::net.sf.jni4net.utils.JniLocalHandle @__obj, global::net.sf.jni4net.utils.JniLocalHandle vals, bool makesUpRow) {
            // ([DZ)V
            // ([DZ)V
            global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.Wrap(@__envp);
            try {
            global::ASquared.Matrix @__real = new global::ASquared.Matrix(global::net.sf.jni4net.utils.Convertor.ArrayPrimJ2Cdouble(@__env, vals), makesUpRow);
            global::net.sf.jni4net.utils.Convertor.InitProxy(@__env, @__obj, @__real);
            }catch (global::System.Exception __ex){@__env.ThrowExisting(__ex);}
        }
        
        private static void @__ctorMatrix7(global::System.IntPtr @__envp, global::net.sf.jni4net.utils.JniLocalHandle @__class, global::net.sf.jni4net.utils.JniLocalHandle @__obj, global::net.sf.jni4net.utils.JniLocalHandle dt) {
            // (Lsystem/Object;)V
            // (LSystem/Data/DataTable;)V
            global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.Wrap(@__envp);
            try {
            global::ASquared.Matrix @__real = new global::ASquared.Matrix(global::net.sf.jni4net.utils.Convertor.StrongJp2C<global::System.Data.DataTable>(@__env, dt));
            global::net.sf.jni4net.utils.Convertor.InitProxy(@__env, @__obj, @__real);
            }catch (global::System.Exception __ex){@__env.ThrowExisting(__ex);}
        }
        
        new internal sealed class ContructionHelper : global::net.sf.jni4net.utils.IConstructionHelper {
            
            public global::net.sf.jni4net.jni.IJvmProxy CreateProxy(global::net.sf.jni4net.jni.JNIEnv @__env) {
                return new global::ASquared.@__Matrix(@__env);
            }
        }
    }
    #endregion
}
